namespace Capa_P
{
    partial class Clientes
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Clientes));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle21 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle22 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle23 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle24 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle25 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties97 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties98 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties99 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties100 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties101 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties102 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties103 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties104 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties105 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties106 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties107 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties108 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties109 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties110 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties111 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties112 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties113 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties114 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties115 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties116 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties117 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties118 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties119 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties120 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuVScrollBar2 = new Bunifu.UI.WinForms.BunifuVScrollBar();
            this.dtaClientes = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnEditar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtFiltro = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnGuardarClienteR = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnborrar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnlimpiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.label6 = new System.Windows.Forms.Label();
            this.txtRnc = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label5 = new System.Windows.Forms.Label();
            this.txtTelefono = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtCliente_CorreoR = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txtCliente_NombreR = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblId = new System.Windows.Forms.Label();
            this.lblNombre = new System.Windows.Forms.Label();
            this.txtDireccion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtaClientes)).BeginInit();
            this.SuspendLayout();
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.White;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(499, 342);
            this.pictureBox1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(21, 18);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 111;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuVScrollBar2
            // 
            this.bunifuVScrollBar2.AllowCursorChanges = true;
            this.bunifuVScrollBar2.AllowHomeEndKeysDetection = false;
            this.bunifuVScrollBar2.AllowIncrementalClickMoves = true;
            this.bunifuVScrollBar2.AllowMouseDownEffects = true;
            this.bunifuVScrollBar2.AllowMouseHoverEffects = true;
            this.bunifuVScrollBar2.AllowScrollingAnimations = true;
            this.bunifuVScrollBar2.AllowScrollKeysDetection = true;
            this.bunifuVScrollBar2.AllowScrollOptionsMenu = true;
            this.bunifuVScrollBar2.AllowShrinkingOnFocusLost = false;
            this.bunifuVScrollBar2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            this.bunifuVScrollBar2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuVScrollBar2.BackgroundImage")));
            this.bunifuVScrollBar2.BindingContainer = null;
            this.bunifuVScrollBar2.BorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.BorderRadius = 6;
            this.bunifuVScrollBar2.BorderThickness = 2;
            this.bunifuVScrollBar2.DurationBeforeShrink = 2000;
            this.bunifuVScrollBar2.LargeChange = 10;
            this.bunifuVScrollBar2.Location = new System.Drawing.Point(1167, 434);
            this.bunifuVScrollBar2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuVScrollBar2.Maximum = 100;
            this.bunifuVScrollBar2.Minimum = 0;
            this.bunifuVScrollBar2.MinimumThumbLength = 18;
            this.bunifuVScrollBar2.Name = "bunifuVScrollBar2";
            this.bunifuVScrollBar2.OnDisable.ScrollBarBorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.OnDisable.ScrollBarColor = System.Drawing.Color.Transparent;
            this.bunifuVScrollBar2.OnDisable.ThumbColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.ScrollBarBorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.ScrollBarColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            this.bunifuVScrollBar2.ShrinkSizeLimit = 3;
            this.bunifuVScrollBar2.Size = new System.Drawing.Size(29, 254);
            this.bunifuVScrollBar2.SmallChange = 1;
            this.bunifuVScrollBar2.TabIndex = 109;
            this.bunifuVScrollBar2.ThumbColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.bunifuVScrollBar2.ThumbLength = 24;
            this.bunifuVScrollBar2.ThumbMargin = 1;
            this.bunifuVScrollBar2.ThumbStyle = Bunifu.UI.WinForms.BunifuVScrollBar.ThumbStyles.Inset;
            this.bunifuVScrollBar2.Value = 0;
            this.bunifuVScrollBar2.Scroll += new System.EventHandler<Bunifu.UI.WinForms.BunifuVScrollBar.ScrollEventArgs>(this.bunifuVScrollBar2_Scroll);
            // 
            // dtaClientes
            // 
            this.dtaClientes.AllowCustomTheming = false;
            this.dtaClientes.AllowUserToAddRows = false;
            this.dtaClientes.AllowUserToDeleteRows = false;
            this.dtaClientes.AllowUserToResizeColumns = false;
            this.dtaClientes.AllowUserToResizeRows = false;
            dataGridViewCellStyle21.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle21.ForeColor = System.Drawing.Color.Black;
            this.dtaClientes.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle21;
            this.dtaClientes.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtaClientes.BackgroundColor = System.Drawing.Color.White;
            this.dtaClientes.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtaClientes.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtaClientes.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle22.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle22.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle22.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle22.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle22.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle22.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle22.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtaClientes.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle22;
            this.dtaClientes.ColumnHeadersHeight = 40;
            this.dtaClientes.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dtaClientes.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtaClientes.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtaClientes.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtaClientes.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dtaClientes.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dtaClientes.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtaClientes.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dtaClientes.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtaClientes.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dtaClientes.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dtaClientes.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dtaClientes.CurrentTheme.Name = null;
            this.dtaClientes.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dtaClientes.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtaClientes.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtaClientes.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtaClientes.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle23.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle23.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle23.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle23.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle23.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle23.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle23.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtaClientes.DefaultCellStyle = dataGridViewCellStyle23;
            this.dtaClientes.EnableHeadersVisualStyles = false;
            this.dtaClientes.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtaClientes.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dtaClientes.HeaderBgColor = System.Drawing.Color.Empty;
            this.dtaClientes.HeaderForeColor = System.Drawing.Color.White;
            this.dtaClientes.Location = new System.Drawing.Point(37, 395);
            this.dtaClientes.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.dtaClientes.Name = "dtaClientes";
            this.dtaClientes.ReadOnly = true;
            this.dtaClientes.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle24.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle24.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            dataGridViewCellStyle24.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle24.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle24.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            dataGridViewCellStyle24.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle24.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtaClientes.RowHeadersDefaultCellStyle = dataGridViewCellStyle24;
            this.dtaClientes.RowHeadersVisible = false;
            this.dtaClientes.RowHeadersWidth = 51;
            this.dtaClientes.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            dataGridViewCellStyle25.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle25.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle25.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle25.SelectionForeColor = System.Drawing.Color.White;
            this.dtaClientes.RowsDefaultCellStyle = dataGridViewCellStyle25;
            this.dtaClientes.RowTemplate.Height = 40;
            this.dtaClientes.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.dtaClientes.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtaClientes.Size = new System.Drawing.Size(1125, 292);
            this.dtaClientes.TabIndex = 108;
            this.dtaClientes.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dtaClientes.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dtaClientes_CellContentClick);
            this.dtaClientes.CellMouseClick += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.dtaClientes_CellMouseClick);
            this.dtaClientes.SelectionChanged += new System.EventHandler(this.dtaClientes_SelectionChanged);
            // 
            // btnEditar
            // 
            this.btnEditar.AllowAnimations = true;
            this.btnEditar.AllowMouseEffects = true;
            this.btnEditar.AllowToggling = false;
            this.btnEditar.AnimationSpeed = 200;
            this.btnEditar.AutoGenerateColors = false;
            this.btnEditar.AutoRoundBorders = false;
            this.btnEditar.AutoSizeLeftIcon = true;
            this.btnEditar.AutoSizeRightIcon = true;
            this.btnEditar.BackColor = System.Drawing.Color.Transparent;
            this.btnEditar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnEditar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEditar.BackgroundImage")));
            this.btnEditar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.ButtonText = "Editar";
            this.btnEditar.ButtonTextMarginLeft = 0;
            this.btnEditar.ColorContrastOnClick = 45;
            this.btnEditar.ColorContrastOnHover = 45;
            this.btnEditar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges21.BottomLeft = true;
            borderEdges21.BottomRight = true;
            borderEdges21.TopLeft = true;
            borderEdges21.TopRight = true;
            this.btnEditar.CustomizableEdges = borderEdges21;
            this.btnEditar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEditar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnEditar.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEditar.ForeColor = System.Drawing.Color.White;
            this.btnEditar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEditar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEditar.IconMarginLeft = 11;
            this.btnEditar.IconPadding = 10;
            this.btnEditar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEditar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEditar.IconSize = 25;
            this.btnEditar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnEditar.IdleBorderRadius = 20;
            this.btnEditar.IdleBorderThickness = 1;
            this.btnEditar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnEditar.IdleIconLeftImage = null;
            this.btnEditar.IdleIconRightImage = null;
            this.btnEditar.IndicateFocus = false;
            this.btnEditar.Location = new System.Drawing.Point(549, 338);
            this.btnEditar.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnEditar.Name = "btnEditar";
            this.btnEditar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditar.OnDisabledState.BorderRadius = 20;
            this.btnEditar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.OnDisabledState.BorderThickness = 1;
            this.btnEditar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditar.OnDisabledState.IconLeftImage = null;
            this.btnEditar.OnDisabledState.IconRightImage = null;
            this.btnEditar.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnEditar.onHoverState.BorderRadius = 20;
            this.btnEditar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.onHoverState.BorderThickness = 1;
            this.btnEditar.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnEditar.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnEditar.onHoverState.IconLeftImage = null;
            this.btnEditar.onHoverState.IconRightImage = null;
            this.btnEditar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnEditar.OnIdleState.BorderRadius = 20;
            this.btnEditar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.OnIdleState.BorderThickness = 1;
            this.btnEditar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnEditar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEditar.OnIdleState.IconLeftImage = null;
            this.btnEditar.OnIdleState.IconRightImage = null;
            this.btnEditar.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnEditar.OnPressedState.BorderRadius = 20;
            this.btnEditar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.OnPressedState.BorderThickness = 1;
            this.btnEditar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnEditar.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btnEditar.OnPressedState.IconLeftImage = null;
            this.btnEditar.OnPressedState.IconRightImage = null;
            this.btnEditar.Size = new System.Drawing.Size(119, 30);
            this.btnEditar.TabIndex = 110;
            this.btnEditar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEditar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEditar.TextMarginLeft = 0;
            this.btnEditar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEditar.UseDefaultRadiusAndThickness = true;
            this.btnEditar.Click += new System.EventHandler(this.btnEditar_Click);
            // 
            // txtFiltro
            // 
            this.txtFiltro.AcceptsReturn = false;
            this.txtFiltro.AcceptsTab = false;
            this.txtFiltro.AnimationSpeed = 200;
            this.txtFiltro.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFiltro.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFiltro.AutoSizeHeight = true;
            this.txtFiltro.BackColor = System.Drawing.Color.Transparent;
            this.txtFiltro.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFiltro.BackgroundImage")));
            this.txtFiltro.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFiltro.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFiltro.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFiltro.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtFiltro.BorderRadius = 20;
            this.txtFiltro.BorderThickness = 1;
            this.txtFiltro.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtFiltro.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFiltro.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltro.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFiltro.DefaultText = "";
            this.txtFiltro.FillColor = System.Drawing.Color.White;
            this.txtFiltro.HideSelection = true;
            this.txtFiltro.IconLeft = null;
            this.txtFiltro.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltro.IconPadding = 10;
            this.txtFiltro.IconRight = null;
            this.txtFiltro.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltro.Lines = new string[0];
            this.txtFiltro.Location = new System.Drawing.Point(48, 332);
            this.txtFiltro.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtFiltro.MaxLength = 32767;
            this.txtFiltro.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFiltro.Modified = false;
            this.txtFiltro.Multiline = false;
            this.txtFiltro.Name = "txtFiltro";
            stateProperties97.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties97.FillColor = System.Drawing.Color.Empty;
            stateProperties97.ForeColor = System.Drawing.Color.Empty;
            stateProperties97.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltro.OnActiveState = stateProperties97;
            stateProperties98.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties98.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties98.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties98.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFiltro.OnDisabledState = stateProperties98;
            stateProperties99.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties99.FillColor = System.Drawing.Color.Empty;
            stateProperties99.ForeColor = System.Drawing.Color.Empty;
            stateProperties99.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltro.OnHoverState = stateProperties99;
            stateProperties100.BorderColor = System.Drawing.Color.Transparent;
            stateProperties100.FillColor = System.Drawing.Color.White;
            stateProperties100.ForeColor = System.Drawing.Color.Empty;
            stateProperties100.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltro.OnIdleState = stateProperties100;
            this.txtFiltro.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtFiltro.PasswordChar = '\0';
            this.txtFiltro.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFiltro.PlaceholderText = "Buscar";
            this.txtFiltro.ReadOnly = false;
            this.txtFiltro.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFiltro.SelectedText = "";
            this.txtFiltro.SelectionLength = 0;
            this.txtFiltro.SelectionStart = 0;
            this.txtFiltro.ShortcutsEnabled = true;
            this.txtFiltro.Size = new System.Drawing.Size(496, 38);
            this.txtFiltro.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFiltro.TabIndex = 97;
            this.txtFiltro.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFiltro.TextMarginBottom = 0;
            this.txtFiltro.TextMarginLeft = 3;
            this.txtFiltro.TextMarginTop = 1;
            this.txtFiltro.TextPlaceholder = "Buscar";
            this.txtFiltro.UseSystemPasswordChar = false;
            this.txtFiltro.WordWrap = true;
            this.txtFiltro.TextChanged += new System.EventHandler(this.txtFiltro_TextChanged);
            // 
            // btnGuardarClienteR
            // 
            this.btnGuardarClienteR.AllowAnimations = true;
            this.btnGuardarClienteR.AllowMouseEffects = true;
            this.btnGuardarClienteR.AllowToggling = false;
            this.btnGuardarClienteR.AnimationSpeed = 200;
            this.btnGuardarClienteR.AutoGenerateColors = false;
            this.btnGuardarClienteR.AutoRoundBorders = false;
            this.btnGuardarClienteR.AutoSizeLeftIcon = true;
            this.btnGuardarClienteR.AutoSizeRightIcon = true;
            this.btnGuardarClienteR.BackColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuardarClienteR.BackgroundImage")));
            this.btnGuardarClienteR.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.ButtonText = "Guardar";
            this.btnGuardarClienteR.ButtonTextMarginLeft = 0;
            this.btnGuardarClienteR.ColorContrastOnClick = 45;
            this.btnGuardarClienteR.ColorContrastOnHover = 45;
            this.btnGuardarClienteR.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges22.BottomLeft = true;
            borderEdges22.BottomRight = true;
            borderEdges22.TopLeft = true;
            borderEdges22.TopRight = true;
            this.btnGuardarClienteR.CustomizableEdges = borderEdges22;
            this.btnGuardarClienteR.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuardarClienteR.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardarClienteR.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardarClienteR.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardarClienteR.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnGuardarClienteR.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardarClienteR.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuardarClienteR.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardarClienteR.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGuardarClienteR.IconMarginLeft = 11;
            this.btnGuardarClienteR.IconPadding = 10;
            this.btnGuardarClienteR.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGuardarClienteR.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardarClienteR.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGuardarClienteR.IconSize = 25;
            this.btnGuardarClienteR.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.IdleBorderRadius = 20;
            this.btnGuardarClienteR.IdleBorderThickness = 1;
            this.btnGuardarClienteR.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.IdleIconLeftImage = null;
            this.btnGuardarClienteR.IdleIconRightImage = null;
            this.btnGuardarClienteR.IndicateFocus = false;
            this.btnGuardarClienteR.Location = new System.Drawing.Point(820, 207);
            this.btnGuardarClienteR.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnGuardarClienteR.Name = "btnGuardarClienteR";
            this.btnGuardarClienteR.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardarClienteR.OnDisabledState.BorderRadius = 20;
            this.btnGuardarClienteR.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnDisabledState.BorderThickness = 1;
            this.btnGuardarClienteR.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardarClienteR.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardarClienteR.OnDisabledState.IconLeftImage = null;
            this.btnGuardarClienteR.OnDisabledState.IconRightImage = null;
            this.btnGuardarClienteR.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.onHoverState.BorderRadius = 20;
            this.btnGuardarClienteR.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.onHoverState.BorderThickness = 1;
            this.btnGuardarClienteR.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnGuardarClienteR.onHoverState.IconLeftImage = null;
            this.btnGuardarClienteR.onHoverState.IconRightImage = null;
            this.btnGuardarClienteR.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.OnIdleState.BorderRadius = 20;
            this.btnGuardarClienteR.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnIdleState.BorderThickness = 1;
            this.btnGuardarClienteR.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.OnIdleState.IconLeftImage = null;
            this.btnGuardarClienteR.OnIdleState.IconRightImage = null;
            this.btnGuardarClienteR.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnPressedState.BorderRadius = 20;
            this.btnGuardarClienteR.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnPressedState.BorderThickness = 1;
            this.btnGuardarClienteR.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.OnPressedState.IconLeftImage = null;
            this.btnGuardarClienteR.OnPressedState.IconRightImage = null;
            this.btnGuardarClienteR.Size = new System.Drawing.Size(233, 44);
            this.btnGuardarClienteR.TabIndex = 99;
            this.btnGuardarClienteR.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuardarClienteR.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGuardarClienteR.TextMarginLeft = 0;
            this.btnGuardarClienteR.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGuardarClienteR.UseDefaultRadiusAndThickness = true;
            this.btnGuardarClienteR.Click += new System.EventHandler(this.btnGuardarClienteR_Click);
            // 
            // btnborrar
            // 
            this.btnborrar.AllowAnimations = true;
            this.btnborrar.AllowMouseEffects = true;
            this.btnborrar.AllowToggling = false;
            this.btnborrar.AnimationSpeed = 200;
            this.btnborrar.AutoGenerateColors = false;
            this.btnborrar.AutoRoundBorders = false;
            this.btnborrar.AutoSizeLeftIcon = true;
            this.btnborrar.AutoSizeRightIcon = true;
            this.btnborrar.BackColor = System.Drawing.Color.Transparent;
            this.btnborrar.BackColor1 = System.Drawing.Color.Red;
            this.btnborrar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnborrar.BackgroundImage")));
            this.btnborrar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.ButtonText = "Borrar";
            this.btnborrar.ButtonTextMarginLeft = 0;
            this.btnborrar.ColorContrastOnClick = 45;
            this.btnborrar.ColorContrastOnHover = 45;
            this.btnborrar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges23.BottomLeft = true;
            borderEdges23.BottomRight = true;
            borderEdges23.TopLeft = true;
            borderEdges23.TopRight = true;
            this.btnborrar.CustomizableEdges = borderEdges23;
            this.btnborrar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnborrar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnborrar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnborrar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnborrar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnborrar.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnborrar.ForeColor = System.Drawing.Color.White;
            this.btnborrar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnborrar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnborrar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnborrar.IconMarginLeft = 11;
            this.btnborrar.IconPadding = 10;
            this.btnborrar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnborrar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnborrar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnborrar.IconSize = 25;
            this.btnborrar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnborrar.IdleBorderRadius = 20;
            this.btnborrar.IdleBorderThickness = 1;
            this.btnborrar.IdleFillColor = System.Drawing.Color.Red;
            this.btnborrar.IdleIconLeftImage = null;
            this.btnborrar.IdleIconRightImage = null;
            this.btnborrar.IndicateFocus = false;
            this.btnborrar.Location = new System.Drawing.Point(665, 252);
            this.btnborrar.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnborrar.Name = "btnborrar";
            this.btnborrar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnborrar.OnDisabledState.BorderRadius = 20;
            this.btnborrar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.OnDisabledState.BorderThickness = 1;
            this.btnborrar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnborrar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnborrar.OnDisabledState.IconLeftImage = null;
            this.btnborrar.OnDisabledState.IconRightImage = null;
            this.btnborrar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnborrar.onHoverState.BorderRadius = 20;
            this.btnborrar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.onHoverState.BorderThickness = 1;
            this.btnborrar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnborrar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnborrar.onHoverState.IconLeftImage = null;
            this.btnborrar.onHoverState.IconRightImage = null;
            this.btnborrar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnborrar.OnIdleState.BorderRadius = 20;
            this.btnborrar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.OnIdleState.BorderThickness = 1;
            this.btnborrar.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.btnborrar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnborrar.OnIdleState.IconLeftImage = null;
            this.btnborrar.OnIdleState.IconRightImage = null;
            this.btnborrar.OnPressedState.BorderColor = System.Drawing.Color.Red;
            this.btnborrar.OnPressedState.BorderRadius = 20;
            this.btnborrar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.OnPressedState.BorderThickness = 1;
            this.btnborrar.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.btnborrar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnborrar.OnPressedState.IconLeftImage = null;
            this.btnborrar.OnPressedState.IconRightImage = null;
            this.btnborrar.Size = new System.Drawing.Size(119, 30);
            this.btnborrar.TabIndex = 107;
            this.btnborrar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnborrar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnborrar.TextMarginLeft = 0;
            this.btnborrar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnborrar.UseDefaultRadiusAndThickness = true;
            this.btnborrar.Click += new System.EventHandler(this.btnborrar_Click);
            // 
            // btnlimpiar
            // 
            this.btnlimpiar.AllowAnimations = true;
            this.btnlimpiar.AllowMouseEffects = true;
            this.btnlimpiar.AllowToggling = false;
            this.btnlimpiar.AnimationSpeed = 200;
            this.btnlimpiar.AutoGenerateColors = false;
            this.btnlimpiar.AutoRoundBorders = false;
            this.btnlimpiar.AutoSizeLeftIcon = true;
            this.btnlimpiar.AutoSizeRightIcon = true;
            this.btnlimpiar.BackColor = System.Drawing.Color.Transparent;
            this.btnlimpiar.BackColor1 = System.Drawing.Color.White;
            this.btnlimpiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnlimpiar.BackgroundImage")));
            this.btnlimpiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.ButtonText = "Limpiar";
            this.btnlimpiar.ButtonTextMarginLeft = 0;
            this.btnlimpiar.ColorContrastOnClick = 45;
            this.btnlimpiar.ColorContrastOnHover = 45;
            this.btnlimpiar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges24.BottomLeft = true;
            borderEdges24.BottomRight = true;
            borderEdges24.TopLeft = true;
            borderEdges24.TopRight = true;
            this.btnlimpiar.CustomizableEdges = borderEdges24;
            this.btnlimpiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnlimpiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnlimpiar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnlimpiar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnlimpiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnlimpiar.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnlimpiar.ForeColor = System.Drawing.Color.DimGray;
            this.btnlimpiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnlimpiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnlimpiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnlimpiar.IconMarginLeft = 11;
            this.btnlimpiar.IconPadding = 10;
            this.btnlimpiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnlimpiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnlimpiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnlimpiar.IconSize = 25;
            this.btnlimpiar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnlimpiar.IdleBorderRadius = 20;
            this.btnlimpiar.IdleBorderThickness = 1;
            this.btnlimpiar.IdleFillColor = System.Drawing.Color.White;
            this.btnlimpiar.IdleIconLeftImage = null;
            this.btnlimpiar.IdleIconRightImage = null;
            this.btnlimpiar.IndicateFocus = false;
            this.btnlimpiar.Location = new System.Drawing.Point(665, 208);
            this.btnlimpiar.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnlimpiar.Name = "btnlimpiar";
            this.btnlimpiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnlimpiar.OnDisabledState.BorderRadius = 20;
            this.btnlimpiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.OnDisabledState.BorderThickness = 1;
            this.btnlimpiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnlimpiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnlimpiar.OnDisabledState.IconLeftImage = null;
            this.btnlimpiar.OnDisabledState.IconRightImage = null;
            this.btnlimpiar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(170)))), ((int)(((byte)(170)))));
            this.btnlimpiar.onHoverState.BorderRadius = 20;
            this.btnlimpiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.onHoverState.BorderThickness = 1;
            this.btnlimpiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(170)))), ((int)(((byte)(170)))));
            this.btnlimpiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnlimpiar.onHoverState.IconLeftImage = null;
            this.btnlimpiar.onHoverState.IconRightImage = null;
            this.btnlimpiar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnlimpiar.OnIdleState.BorderRadius = 20;
            this.btnlimpiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.OnIdleState.BorderThickness = 1;
            this.btnlimpiar.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnlimpiar.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btnlimpiar.OnIdleState.IconLeftImage = null;
            this.btnlimpiar.OnIdleState.IconRightImage = null;
            this.btnlimpiar.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnlimpiar.OnPressedState.BorderRadius = 20;
            this.btnlimpiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.OnPressedState.BorderThickness = 1;
            this.btnlimpiar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnlimpiar.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btnlimpiar.OnPressedState.IconLeftImage = null;
            this.btnlimpiar.OnPressedState.IconRightImage = null;
            this.btnlimpiar.Size = new System.Drawing.Size(119, 30);
            this.btnlimpiar.TabIndex = 103;
            this.btnlimpiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnlimpiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnlimpiar.TextMarginLeft = 0;
            this.btnlimpiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnlimpiar.UseDefaultRadiusAndThickness = true;
            // 
            // label6
            // 
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.label6.Location = new System.Drawing.Point(400, 178);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(108, 27);
            this.label6.TabIndex = 106;
            this.label6.Text = "Direccion";
            this.label6.Click += new System.EventHandler(this.label6_Click);
            // 
            // txtRnc
            // 
            this.txtRnc.AcceptsReturn = false;
            this.txtRnc.AcceptsTab = false;
            this.txtRnc.AnimationSpeed = 200;
            this.txtRnc.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtRnc.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtRnc.AutoSizeHeight = true;
            this.txtRnc.BackColor = System.Drawing.Color.Transparent;
            this.txtRnc.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtRnc.BackgroundImage")));
            this.txtRnc.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtRnc.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtRnc.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtRnc.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtRnc.BorderRadius = 20;
            this.txtRnc.BorderThickness = 1;
            this.txtRnc.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtRnc.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtRnc.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRnc.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtRnc.DefaultText = "";
            this.txtRnc.FillColor = System.Drawing.Color.White;
            this.txtRnc.HideSelection = true;
            this.txtRnc.IconLeft = null;
            this.txtRnc.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRnc.IconPadding = 10;
            this.txtRnc.IconRight = null;
            this.txtRnc.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtRnc.Lines = new string[0];
            this.txtRnc.Location = new System.Drawing.Point(43, 208);
            this.txtRnc.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtRnc.MaxLength = 32767;
            this.txtRnc.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtRnc.Modified = false;
            this.txtRnc.Multiline = false;
            this.txtRnc.Name = "txtRnc";
            stateProperties101.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties101.FillColor = System.Drawing.Color.Empty;
            stateProperties101.ForeColor = System.Drawing.Color.Empty;
            stateProperties101.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRnc.OnActiveState = stateProperties101;
            stateProperties102.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties102.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties102.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties102.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtRnc.OnDisabledState = stateProperties102;
            stateProperties103.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties103.FillColor = System.Drawing.Color.Empty;
            stateProperties103.ForeColor = System.Drawing.Color.Empty;
            stateProperties103.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRnc.OnHoverState = stateProperties103;
            stateProperties104.BorderColor = System.Drawing.Color.Transparent;
            stateProperties104.FillColor = System.Drawing.Color.White;
            stateProperties104.ForeColor = System.Drawing.Color.Empty;
            stateProperties104.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtRnc.OnIdleState = stateProperties104;
            this.txtRnc.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtRnc.PasswordChar = '\0';
            this.txtRnc.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtRnc.PlaceholderText = "";
            this.txtRnc.ReadOnly = false;
            this.txtRnc.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtRnc.SelectedText = "";
            this.txtRnc.SelectionLength = 0;
            this.txtRnc.SelectionStart = 0;
            this.txtRnc.ShortcutsEnabled = true;
            this.txtRnc.Size = new System.Drawing.Size(317, 34);
            this.txtRnc.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtRnc.TabIndex = 96;
            this.txtRnc.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtRnc.TextMarginBottom = 0;
            this.txtRnc.TextMarginLeft = 3;
            this.txtRnc.TextMarginTop = 1;
            this.txtRnc.TextPlaceholder = "";
            this.txtRnc.UseSystemPasswordChar = false;
            this.txtRnc.WordWrap = true;
            // 
            // label5
            // 
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.label5.Location = new System.Drawing.Point(47, 178);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(108, 27);
            this.label5.TabIndex = 105;
            this.label5.Text = "RNC";
            // 
            // txtTelefono
            // 
            this.txtTelefono.AcceptsReturn = false;
            this.txtTelefono.AcceptsTab = false;
            this.txtTelefono.AnimationSpeed = 200;
            this.txtTelefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTelefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTelefono.AutoSizeHeight = true;
            this.txtTelefono.BackColor = System.Drawing.Color.Transparent;
            this.txtTelefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTelefono.BackgroundImage")));
            this.txtTelefono.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTelefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTelefono.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTelefono.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtTelefono.BorderRadius = 20;
            this.txtTelefono.BorderThickness = 1;
            this.txtTelefono.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtTelefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTelefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTelefono.DefaultText = "";
            this.txtTelefono.FillColor = System.Drawing.Color.White;
            this.txtTelefono.HideSelection = true;
            this.txtTelefono.IconLeft = null;
            this.txtTelefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.IconPadding = 10;
            this.txtTelefono.IconRight = null;
            this.txtTelefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.Lines = new string[0];
            this.txtTelefono.Location = new System.Drawing.Point(725, 128);
            this.txtTelefono.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtTelefono.MaxLength = 32767;
            this.txtTelefono.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTelefono.Modified = false;
            this.txtTelefono.Multiline = false;
            this.txtTelefono.Name = "txtTelefono";
            stateProperties105.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties105.FillColor = System.Drawing.Color.Empty;
            stateProperties105.ForeColor = System.Drawing.Color.Empty;
            stateProperties105.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnActiveState = stateProperties105;
            stateProperties106.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties106.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties106.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties106.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTelefono.OnDisabledState = stateProperties106;
            stateProperties107.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties107.FillColor = System.Drawing.Color.Empty;
            stateProperties107.ForeColor = System.Drawing.Color.Empty;
            stateProperties107.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnHoverState = stateProperties107;
            stateProperties108.BorderColor = System.Drawing.Color.Transparent;
            stateProperties108.FillColor = System.Drawing.Color.White;
            stateProperties108.ForeColor = System.Drawing.Color.Empty;
            stateProperties108.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnIdleState = stateProperties108;
            this.txtTelefono.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtTelefono.PasswordChar = '\0';
            this.txtTelefono.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTelefono.PlaceholderText = "";
            this.txtTelefono.ReadOnly = false;
            this.txtTelefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTelefono.SelectedText = "";
            this.txtTelefono.SelectionLength = 0;
            this.txtTelefono.SelectionStart = 0;
            this.txtTelefono.ShortcutsEnabled = true;
            this.txtTelefono.Size = new System.Drawing.Size(317, 34);
            this.txtTelefono.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTelefono.TabIndex = 95;
            this.txtTelefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTelefono.TextMarginBottom = 0;
            this.txtTelefono.TextMarginLeft = 3;
            this.txtTelefono.TextMarginTop = 1;
            this.txtTelefono.TextPlaceholder = "";
            this.txtTelefono.UseSystemPasswordChar = false;
            this.txtTelefono.WordWrap = true;
            this.txtTelefono.TextChange += new System.EventHandler(this.txtTelefono_TextChange);
            // 
            // label4
            // 
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.label4.Location = new System.Drawing.Point(731, 98);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(108, 27);
            this.label4.TabIndex = 104;
            this.label4.Text = "Telefono";
            // 
            // txtCliente_CorreoR
            // 
            this.txtCliente_CorreoR.AcceptsReturn = false;
            this.txtCliente_CorreoR.AcceptsTab = false;
            this.txtCliente_CorreoR.AnimationSpeed = 200;
            this.txtCliente_CorreoR.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCliente_CorreoR.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCliente_CorreoR.AutoSizeHeight = true;
            this.txtCliente_CorreoR.BackColor = System.Drawing.Color.Transparent;
            this.txtCliente_CorreoR.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCliente_CorreoR.BackgroundImage")));
            this.txtCliente_CorreoR.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCliente_CorreoR.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCliente_CorreoR.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCliente_CorreoR.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtCliente_CorreoR.BorderRadius = 20;
            this.txtCliente_CorreoR.BorderThickness = 1;
            this.txtCliente_CorreoR.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCliente_CorreoR.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCliente_CorreoR.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCliente_CorreoR.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCliente_CorreoR.DefaultText = "";
            this.txtCliente_CorreoR.FillColor = System.Drawing.Color.White;
            this.txtCliente_CorreoR.HideSelection = true;
            this.txtCliente_CorreoR.IconLeft = null;
            this.txtCliente_CorreoR.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCliente_CorreoR.IconPadding = 10;
            this.txtCliente_CorreoR.IconRight = null;
            this.txtCliente_CorreoR.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCliente_CorreoR.Lines = new string[0];
            this.txtCliente_CorreoR.Location = new System.Drawing.Point(385, 128);
            this.txtCliente_CorreoR.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtCliente_CorreoR.MaxLength = 32767;
            this.txtCliente_CorreoR.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCliente_CorreoR.Modified = false;
            this.txtCliente_CorreoR.Multiline = false;
            this.txtCliente_CorreoR.Name = "txtCliente_CorreoR";
            stateProperties109.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties109.FillColor = System.Drawing.Color.Empty;
            stateProperties109.ForeColor = System.Drawing.Color.Empty;
            stateProperties109.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCliente_CorreoR.OnActiveState = stateProperties109;
            stateProperties110.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties110.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties110.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties110.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCliente_CorreoR.OnDisabledState = stateProperties110;
            stateProperties111.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties111.FillColor = System.Drawing.Color.Empty;
            stateProperties111.ForeColor = System.Drawing.Color.Empty;
            stateProperties111.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCliente_CorreoR.OnHoverState = stateProperties111;
            stateProperties112.BorderColor = System.Drawing.Color.Transparent;
            stateProperties112.FillColor = System.Drawing.Color.White;
            stateProperties112.ForeColor = System.Drawing.Color.Empty;
            stateProperties112.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCliente_CorreoR.OnIdleState = stateProperties112;
            this.txtCliente_CorreoR.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtCliente_CorreoR.PasswordChar = '\0';
            this.txtCliente_CorreoR.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCliente_CorreoR.PlaceholderText = "";
            this.txtCliente_CorreoR.ReadOnly = false;
            this.txtCliente_CorreoR.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCliente_CorreoR.SelectedText = "";
            this.txtCliente_CorreoR.SelectionLength = 0;
            this.txtCliente_CorreoR.SelectionStart = 0;
            this.txtCliente_CorreoR.ShortcutsEnabled = true;
            this.txtCliente_CorreoR.Size = new System.Drawing.Size(317, 34);
            this.txtCliente_CorreoR.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCliente_CorreoR.TabIndex = 94;
            this.txtCliente_CorreoR.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCliente_CorreoR.TextMarginBottom = 0;
            this.txtCliente_CorreoR.TextMarginLeft = 3;
            this.txtCliente_CorreoR.TextMarginTop = 1;
            this.txtCliente_CorreoR.TextPlaceholder = "";
            this.txtCliente_CorreoR.UseSystemPasswordChar = false;
            this.txtCliente_CorreoR.WordWrap = true;
            // 
            // label1
            // 
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.label1.Location = new System.Drawing.Point(389, 98);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(108, 27);
            this.label1.TabIndex = 102;
            this.label1.Text = "Correo";
            // 
            // txtCliente_NombreR
            // 
            this.txtCliente_NombreR.AcceptsReturn = false;
            this.txtCliente_NombreR.AcceptsTab = false;
            this.txtCliente_NombreR.AnimationSpeed = 200;
            this.txtCliente_NombreR.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCliente_NombreR.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCliente_NombreR.AutoSizeHeight = true;
            this.txtCliente_NombreR.BackColor = System.Drawing.Color.Transparent;
            this.txtCliente_NombreR.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCliente_NombreR.BackgroundImage")));
            this.txtCliente_NombreR.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCliente_NombreR.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCliente_NombreR.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCliente_NombreR.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtCliente_NombreR.BorderRadius = 20;
            this.txtCliente_NombreR.BorderThickness = 1;
            this.txtCliente_NombreR.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCliente_NombreR.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCliente_NombreR.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCliente_NombreR.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCliente_NombreR.DefaultText = "";
            this.txtCliente_NombreR.FillColor = System.Drawing.Color.White;
            this.txtCliente_NombreR.HideSelection = true;
            this.txtCliente_NombreR.IconLeft = null;
            this.txtCliente_NombreR.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCliente_NombreR.IconPadding = 10;
            this.txtCliente_NombreR.IconRight = null;
            this.txtCliente_NombreR.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCliente_NombreR.Lines = new string[0];
            this.txtCliente_NombreR.Location = new System.Drawing.Point(43, 128);
            this.txtCliente_NombreR.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtCliente_NombreR.MaxLength = 32767;
            this.txtCliente_NombreR.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCliente_NombreR.Modified = false;
            this.txtCliente_NombreR.Multiline = false;
            this.txtCliente_NombreR.Name = "txtCliente_NombreR";
            stateProperties113.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties113.FillColor = System.Drawing.Color.Empty;
            stateProperties113.ForeColor = System.Drawing.Color.Empty;
            stateProperties113.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCliente_NombreR.OnActiveState = stateProperties113;
            stateProperties114.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties114.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties114.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties114.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCliente_NombreR.OnDisabledState = stateProperties114;
            stateProperties115.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties115.FillColor = System.Drawing.Color.Empty;
            stateProperties115.ForeColor = System.Drawing.Color.Empty;
            stateProperties115.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCliente_NombreR.OnHoverState = stateProperties115;
            stateProperties116.BorderColor = System.Drawing.Color.Transparent;
            stateProperties116.FillColor = System.Drawing.Color.White;
            stateProperties116.ForeColor = System.Drawing.Color.Empty;
            stateProperties116.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCliente_NombreR.OnIdleState = stateProperties116;
            this.txtCliente_NombreR.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtCliente_NombreR.PasswordChar = '\0';
            this.txtCliente_NombreR.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCliente_NombreR.PlaceholderText = "";
            this.txtCliente_NombreR.ReadOnly = false;
            this.txtCliente_NombreR.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCliente_NombreR.SelectedText = "";
            this.txtCliente_NombreR.SelectionLength = 0;
            this.txtCliente_NombreR.SelectionStart = 0;
            this.txtCliente_NombreR.ShortcutsEnabled = true;
            this.txtCliente_NombreR.Size = new System.Drawing.Size(317, 34);
            this.txtCliente_NombreR.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCliente_NombreR.TabIndex = 93;
            this.txtCliente_NombreR.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCliente_NombreR.TextMarginBottom = 0;
            this.txtCliente_NombreR.TextMarginLeft = 3;
            this.txtCliente_NombreR.TextMarginTop = 1;
            this.txtCliente_NombreR.TextPlaceholder = "";
            this.txtCliente_NombreR.UseSystemPasswordChar = false;
            this.txtCliente_NombreR.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 16.2F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.bunifuLabel2.Location = new System.Drawing.Point(48, 26);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(107, 31);
            this.bunifuLabel2.TabIndex = 101;
            this.bunifuLabel2.Text = "Clientes";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblId
            // 
            this.lblId.BackColor = System.Drawing.Color.White;
            this.lblId.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblId.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblId.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.lblId.Location = new System.Drawing.Point(893, 48);
            this.lblId.Name = "lblId";
            this.lblId.Size = new System.Drawing.Size(141, 25);
            this.lblId.TabIndex = 100;
            this.lblId.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblId.Visible = false;
            // 
            // lblNombre
            // 
            this.lblNombre.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNombre.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.lblNombre.Location = new System.Drawing.Point(47, 98);
            this.lblNombre.Name = "lblNombre";
            this.lblNombre.Size = new System.Drawing.Size(105, 25);
            this.lblNombre.TabIndex = 92;
            this.lblNombre.Text = "Nombre";
            // 
            // txtDireccion
            // 
            this.txtDireccion.AcceptsReturn = false;
            this.txtDireccion.AcceptsTab = false;
            this.txtDireccion.AnimationSpeed = 200;
            this.txtDireccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDireccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDireccion.AutoSizeHeight = true;
            this.txtDireccion.BackColor = System.Drawing.Color.Transparent;
            this.txtDireccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDireccion.BackgroundImage")));
            this.txtDireccion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDireccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDireccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDireccion.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtDireccion.BorderRadius = 20;
            this.txtDireccion.BorderThickness = 1;
            this.txtDireccion.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDireccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDireccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDireccion.DefaultText = "";
            this.txtDireccion.FillColor = System.Drawing.Color.White;
            this.txtDireccion.HideSelection = true;
            this.txtDireccion.IconLeft = null;
            this.txtDireccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.IconPadding = 10;
            this.txtDireccion.IconRight = null;
            this.txtDireccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.Lines = new string[0];
            this.txtDireccion.Location = new System.Drawing.Point(385, 208);
            this.txtDireccion.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtDireccion.MaxLength = 32767;
            this.txtDireccion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDireccion.Modified = false;
            this.txtDireccion.Multiline = false;
            this.txtDireccion.Name = "txtDireccion";
            stateProperties117.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties117.FillColor = System.Drawing.Color.Empty;
            stateProperties117.ForeColor = System.Drawing.Color.Empty;
            stateProperties117.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnActiveState = stateProperties117;
            stateProperties118.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties118.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties118.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties118.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDireccion.OnDisabledState = stateProperties118;
            stateProperties119.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties119.FillColor = System.Drawing.Color.Empty;
            stateProperties119.ForeColor = System.Drawing.Color.Empty;
            stateProperties119.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnHoverState = stateProperties119;
            stateProperties120.BorderColor = System.Drawing.Color.Transparent;
            stateProperties120.FillColor = System.Drawing.Color.White;
            stateProperties120.ForeColor = System.Drawing.Color.Empty;
            stateProperties120.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnIdleState = stateProperties120;
            this.txtDireccion.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtDireccion.PasswordChar = '\0';
            this.txtDireccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDireccion.PlaceholderText = "";
            this.txtDireccion.ReadOnly = false;
            this.txtDireccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDireccion.SelectedText = "";
            this.txtDireccion.SelectionLength = 0;
            this.txtDireccion.SelectionStart = 0;
            this.txtDireccion.ShortcutsEnabled = true;
            this.txtDireccion.Size = new System.Drawing.Size(255, 34);
            this.txtDireccion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDireccion.TabIndex = 112;
            this.txtDireccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDireccion.TextMarginBottom = 0;
            this.txtDireccion.TextMarginLeft = 3;
            this.txtDireccion.TextMarginTop = 1;
            this.txtDireccion.TextPlaceholder = "";
            this.txtDireccion.UseSystemPasswordChar = false;
            this.txtDireccion.WordWrap = true;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Exportar";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges25.BottomLeft = true;
            borderEdges25.BottomRight = true;
            borderEdges25.TopLeft = true;
            borderEdges25.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges25;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.bunifuButton21.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.IdleBorderRadius = 20;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(1044, 342);
            this.bunifuButton21.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 20;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(170)))), ((int)(((byte)(170)))));
            this.bunifuButton21.onHoverState.BorderRadius = 20;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(170)))), ((int)(((byte)(170)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnIdleState.BorderRadius = 20;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.BorderRadius = 20;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(119, 30);
            this.bunifuButton21.TabIndex = 113;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // Clientes
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1460, 738);
            this.Controls.Add(this.bunifuButton21);
            this.Controls.Add(this.txtDireccion);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.bunifuVScrollBar2);
            this.Controls.Add(this.dtaClientes);
            this.Controls.Add(this.btnEditar);
            this.Controls.Add(this.txtFiltro);
            this.Controls.Add(this.btnGuardarClienteR);
            this.Controls.Add(this.btnborrar);
            this.Controls.Add(this.btnlimpiar);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.txtRnc);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.txtTelefono);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.txtCliente_CorreoR);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.txtCliente_NombreR);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.lblId);
            this.Controls.Add(this.lblNombre);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Name = "Clientes";
            this.Text = "Clientescs";
            this.Load += new System.EventHandler(this.Clientes_Load);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtaClientes)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuVScrollBar bunifuVScrollBar2;
        private Bunifu.UI.WinForms.BunifuDataGridView dtaClientes;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnEditar;
        private Bunifu.UI.WinForms.BunifuTextBox txtFiltro;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnGuardarClienteR;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnborrar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnlimpiar;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox txtRnc;
        private System.Windows.Forms.Label label5;
        private Bunifu.UI.WinForms.BunifuTextBox txtTelefono;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox txtCliente_CorreoR;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtCliente_NombreR;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private System.Windows.Forms.Label lblId;
        private System.Windows.Forms.Label lblNombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtDireccion;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
    }
}