namespace Capa_P
{
    partial class Fabricacion
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Fabricacion));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuVScrollBar2 = new Bunifu.UI.WinForms.BunifuVScrollBar();
            this.dtaFacturas = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.btnGuardarClienteR = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtCliente_NombreR = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblNombre = new System.Windows.Forms.Label();
            this.txtTelefono = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtDireccion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label6 = new System.Windows.Forms.Label();
            this.btnBuscarCliente = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.listBox1 = new System.Windows.Forms.ListBox();
            this.label20 = new System.Windows.Forms.Label();
            this.btnImagen = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.openFileDialog1 = new System.Windows.Forms.OpenFileDialog();
            this.txtFechaEntrada = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.txtFechaSalida = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txtFiltroNCF = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.dtaFacturas)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuVScrollBar2
            // 
            this.bunifuVScrollBar2.AllowCursorChanges = true;
            this.bunifuVScrollBar2.AllowHomeEndKeysDetection = false;
            this.bunifuVScrollBar2.AllowIncrementalClickMoves = true;
            this.bunifuVScrollBar2.AllowMouseDownEffects = true;
            this.bunifuVScrollBar2.AllowMouseHoverEffects = true;
            this.bunifuVScrollBar2.AllowScrollingAnimations = true;
            this.bunifuVScrollBar2.AllowScrollKeysDetection = true;
            this.bunifuVScrollBar2.AllowScrollOptionsMenu = true;
            this.bunifuVScrollBar2.AllowShrinkingOnFocusLost = false;
            this.bunifuVScrollBar2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            this.bunifuVScrollBar2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuVScrollBar2.BackgroundImage")));
            this.bunifuVScrollBar2.BindingContainer = null;
            this.bunifuVScrollBar2.BorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.BorderRadius = 6;
            this.bunifuVScrollBar2.BorderThickness = 2;
            this.bunifuVScrollBar2.DurationBeforeShrink = 2000;
            this.bunifuVScrollBar2.LargeChange = 17;
            this.bunifuVScrollBar2.Location = new System.Drawing.Point(1108, 452);
            this.bunifuVScrollBar2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuVScrollBar2.Maximum = 100;
            this.bunifuVScrollBar2.Minimum = 0;
            this.bunifuVScrollBar2.MinimumThumbLength = 18;
            this.bunifuVScrollBar2.Name = "bunifuVScrollBar2";
            this.bunifuVScrollBar2.OnDisable.ScrollBarBorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.OnDisable.ScrollBarColor = System.Drawing.Color.Transparent;
            this.bunifuVScrollBar2.OnDisable.ThumbColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.ScrollBarBorderColor = System.Drawing.Color.Silver;
            this.bunifuVScrollBar2.ScrollBarColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            this.bunifuVScrollBar2.ShrinkSizeLimit = 3;
            this.bunifuVScrollBar2.Size = new System.Drawing.Size(29, 275);
            this.bunifuVScrollBar2.SmallChange = 1;
            this.bunifuVScrollBar2.TabIndex = 125;
            this.bunifuVScrollBar2.ThumbColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.bunifuVScrollBar2.ThumbLength = 45;
            this.bunifuVScrollBar2.ThumbMargin = 1;
            this.bunifuVScrollBar2.ThumbStyle = Bunifu.UI.WinForms.BunifuVScrollBar.ThumbStyles.Inset;
            this.bunifuVScrollBar2.Value = 0;
            this.bunifuVScrollBar2.Scroll += new System.EventHandler<Bunifu.UI.WinForms.BunifuVScrollBar.ScrollEventArgs>(this.bunifuVScrollBar2_Scroll);
            // 
            // dtaFacturas
            // 
            this.dtaFacturas.AllowCustomTheming = false;
            this.dtaFacturas.AllowUserToAddRows = false;
            this.dtaFacturas.AllowUserToDeleteRows = false;
            this.dtaFacturas.AllowUserToResizeColumns = false;
            this.dtaFacturas.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dtaFacturas.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dtaFacturas.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtaFacturas.BackgroundColor = System.Drawing.Color.White;
            this.dtaFacturas.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtaFacturas.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtaFacturas.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtaFacturas.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dtaFacturas.ColumnHeadersHeight = 40;
            this.dtaFacturas.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dtaFacturas.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtaFacturas.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtaFacturas.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtaFacturas.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dtaFacturas.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dtaFacturas.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtaFacturas.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dtaFacturas.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtaFacturas.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dtaFacturas.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dtaFacturas.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dtaFacturas.CurrentTheme.Name = null;
            this.dtaFacturas.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dtaFacturas.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtaFacturas.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtaFacturas.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtaFacturas.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtaFacturas.DefaultCellStyle = dataGridViewCellStyle3;
            this.dtaFacturas.EnableHeadersVisualStyles = false;
            this.dtaFacturas.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtaFacturas.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dtaFacturas.HeaderBgColor = System.Drawing.Color.Empty;
            this.dtaFacturas.HeaderForeColor = System.Drawing.Color.White;
            this.dtaFacturas.Location = new System.Drawing.Point(56, 452);
            this.dtaFacturas.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.dtaFacturas.Name = "dtaFacturas";
            this.dtaFacturas.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtaFacturas.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.dtaFacturas.RowHeadersVisible = false;
            this.dtaFacturas.RowHeadersWidth = 51;
            this.dtaFacturas.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            this.dtaFacturas.RowsDefaultCellStyle = dataGridViewCellStyle5;
            this.dtaFacturas.RowTemplate.Height = 40;
            this.dtaFacturas.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.dtaFacturas.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtaFacturas.Size = new System.Drawing.Size(1046, 275);
            this.dtaFacturas.TabIndex = 124;
            this.dtaFacturas.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dtaFacturas.DoubleClick += new System.EventHandler(this.dtaFacturas_DoubleClick);
            // 
            // btnGuardarClienteR
            // 
            this.btnGuardarClienteR.AllowAnimations = true;
            this.btnGuardarClienteR.AllowMouseEffects = true;
            this.btnGuardarClienteR.AllowToggling = false;
            this.btnGuardarClienteR.AnimationSpeed = 200;
            this.btnGuardarClienteR.AutoGenerateColors = false;
            this.btnGuardarClienteR.AutoRoundBorders = false;
            this.btnGuardarClienteR.AutoSizeLeftIcon = true;
            this.btnGuardarClienteR.AutoSizeRightIcon = true;
            this.btnGuardarClienteR.BackColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuardarClienteR.BackgroundImage")));
            this.btnGuardarClienteR.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.ButtonText = "Imprimir";
            this.btnGuardarClienteR.ButtonTextMarginLeft = 0;
            this.btnGuardarClienteR.ColorContrastOnClick = 45;
            this.btnGuardarClienteR.ColorContrastOnHover = 45;
            this.btnGuardarClienteR.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnGuardarClienteR.CustomizableEdges = borderEdges1;
            this.btnGuardarClienteR.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuardarClienteR.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardarClienteR.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardarClienteR.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardarClienteR.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnGuardarClienteR.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardarClienteR.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuardarClienteR.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardarClienteR.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGuardarClienteR.IconMarginLeft = 11;
            this.btnGuardarClienteR.IconPadding = 10;
            this.btnGuardarClienteR.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGuardarClienteR.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardarClienteR.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGuardarClienteR.IconSize = 25;
            this.btnGuardarClienteR.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.IdleBorderRadius = 20;
            this.btnGuardarClienteR.IdleBorderThickness = 1;
            this.btnGuardarClienteR.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.IdleIconLeftImage = null;
            this.btnGuardarClienteR.IdleIconRightImage = null;
            this.btnGuardarClienteR.IndicateFocus = false;
            this.btnGuardarClienteR.Location = new System.Drawing.Point(961, 391);
            this.btnGuardarClienteR.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnGuardarClienteR.Name = "btnGuardarClienteR";
            this.btnGuardarClienteR.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardarClienteR.OnDisabledState.BorderRadius = 20;
            this.btnGuardarClienteR.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnDisabledState.BorderThickness = 1;
            this.btnGuardarClienteR.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardarClienteR.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardarClienteR.OnDisabledState.IconLeftImage = null;
            this.btnGuardarClienteR.OnDisabledState.IconRightImage = null;
            this.btnGuardarClienteR.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.onHoverState.BorderRadius = 20;
            this.btnGuardarClienteR.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.onHoverState.BorderThickness = 1;
            this.btnGuardarClienteR.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnGuardarClienteR.onHoverState.IconLeftImage = null;
            this.btnGuardarClienteR.onHoverState.IconRightImage = null;
            this.btnGuardarClienteR.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.OnIdleState.BorderRadius = 20;
            this.btnGuardarClienteR.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnIdleState.BorderThickness = 1;
            this.btnGuardarClienteR.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.OnIdleState.IconLeftImage = null;
            this.btnGuardarClienteR.OnIdleState.IconRightImage = null;
            this.btnGuardarClienteR.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnPressedState.BorderRadius = 20;
            this.btnGuardarClienteR.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnPressedState.BorderThickness = 1;
            this.btnGuardarClienteR.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.OnPressedState.IconLeftImage = null;
            this.btnGuardarClienteR.OnPressedState.IconRightImage = null;
            this.btnGuardarClienteR.Size = new System.Drawing.Size(141, 39);
            this.btnGuardarClienteR.TabIndex = 119;
            this.btnGuardarClienteR.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuardarClienteR.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGuardarClienteR.TextMarginLeft = 0;
            this.btnGuardarClienteR.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGuardarClienteR.UseDefaultRadiusAndThickness = true;
            this.btnGuardarClienteR.Click += new System.EventHandler(this.btnGuardarClienteR_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 16.2F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.bunifuLabel2.Location = new System.Drawing.Point(78, 30);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(152, 31);
            this.bunifuLabel2.TabIndex = 116;
            this.bunifuLabel2.Text = "Fabricacion";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtCliente_NombreR
            // 
            this.txtCliente_NombreR.AcceptsReturn = false;
            this.txtCliente_NombreR.AcceptsTab = false;
            this.txtCliente_NombreR.AnimationSpeed = 200;
            this.txtCliente_NombreR.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCliente_NombreR.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCliente_NombreR.AutoSizeHeight = true;
            this.txtCliente_NombreR.BackColor = System.Drawing.Color.Transparent;
            this.txtCliente_NombreR.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCliente_NombreR.BackgroundImage")));
            this.txtCliente_NombreR.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCliente_NombreR.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCliente_NombreR.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCliente_NombreR.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtCliente_NombreR.BorderRadius = 20;
            this.txtCliente_NombreR.BorderThickness = 1;
            this.txtCliente_NombreR.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCliente_NombreR.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCliente_NombreR.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCliente_NombreR.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtCliente_NombreR.DefaultText = "";
            this.txtCliente_NombreR.FillColor = System.Drawing.Color.White;
            this.txtCliente_NombreR.HideSelection = true;
            this.txtCliente_NombreR.IconLeft = null;
            this.txtCliente_NombreR.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCliente_NombreR.IconPadding = 10;
            this.txtCliente_NombreR.IconRight = null;
            this.txtCliente_NombreR.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCliente_NombreR.Lines = new string[0];
            this.txtCliente_NombreR.Location = new System.Drawing.Point(78, 120);
            this.txtCliente_NombreR.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtCliente_NombreR.MaxLength = 32767;
            this.txtCliente_NombreR.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCliente_NombreR.Modified = false;
            this.txtCliente_NombreR.Multiline = false;
            this.txtCliente_NombreR.Name = "txtCliente_NombreR";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCliente_NombreR.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCliente_NombreR.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCliente_NombreR.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Transparent;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCliente_NombreR.OnIdleState = stateProperties4;
            this.txtCliente_NombreR.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtCliente_NombreR.PasswordChar = '\0';
            this.txtCliente_NombreR.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCliente_NombreR.PlaceholderText = "";
            this.txtCliente_NombreR.ReadOnly = false;
            this.txtCliente_NombreR.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCliente_NombreR.SelectedText = "";
            this.txtCliente_NombreR.SelectionLength = 0;
            this.txtCliente_NombreR.SelectionStart = 0;
            this.txtCliente_NombreR.ShortcutsEnabled = true;
            this.txtCliente_NombreR.Size = new System.Drawing.Size(317, 34);
            this.txtCliente_NombreR.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCliente_NombreR.TabIndex = 127;
            this.txtCliente_NombreR.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCliente_NombreR.TextMarginBottom = 0;
            this.txtCliente_NombreR.TextMarginLeft = 3;
            this.txtCliente_NombreR.TextMarginTop = 1;
            this.txtCliente_NombreR.TextPlaceholder = "";
            this.txtCliente_NombreR.UseSystemPasswordChar = false;
            this.txtCliente_NombreR.WordWrap = true;
            // 
            // lblNombre
            // 
            this.lblNombre.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNombre.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.lblNombre.Location = new System.Drawing.Point(76, 93);
            this.lblNombre.Name = "lblNombre";
            this.lblNombre.Size = new System.Drawing.Size(105, 25);
            this.lblNombre.TabIndex = 126;
            this.lblNombre.Text = "Nombre";
            // 
            // txtTelefono
            // 
            this.txtTelefono.AcceptsReturn = false;
            this.txtTelefono.AcceptsTab = false;
            this.txtTelefono.AnimationSpeed = 200;
            this.txtTelefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTelefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTelefono.AutoSizeHeight = true;
            this.txtTelefono.BackColor = System.Drawing.Color.Transparent;
            this.txtTelefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTelefono.BackgroundImage")));
            this.txtTelefono.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTelefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTelefono.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTelefono.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtTelefono.BorderRadius = 20;
            this.txtTelefono.BorderThickness = 1;
            this.txtTelefono.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtTelefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTelefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTelefono.DefaultText = "";
            this.txtTelefono.FillColor = System.Drawing.Color.White;
            this.txtTelefono.HideSelection = true;
            this.txtTelefono.IconLeft = null;
            this.txtTelefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.IconPadding = 10;
            this.txtTelefono.IconRight = null;
            this.txtTelefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefono.Lines = new string[0];
            this.txtTelefono.Location = new System.Drawing.Point(78, 270);
            this.txtTelefono.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtTelefono.MaxLength = 32767;
            this.txtTelefono.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTelefono.Modified = false;
            this.txtTelefono.Multiline = false;
            this.txtTelefono.Name = "txtTelefono";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTelefono.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Transparent;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefono.OnIdleState = stateProperties8;
            this.txtTelefono.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtTelefono.PasswordChar = '\0';
            this.txtTelefono.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTelefono.PlaceholderText = "";
            this.txtTelefono.ReadOnly = false;
            this.txtTelefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTelefono.SelectedText = "";
            this.txtTelefono.SelectionLength = 0;
            this.txtTelefono.SelectionStart = 0;
            this.txtTelefono.ShortcutsEnabled = true;
            this.txtTelefono.Size = new System.Drawing.Size(317, 34);
            this.txtTelefono.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTelefono.TabIndex = 128;
            this.txtTelefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTelefono.TextMarginBottom = 0;
            this.txtTelefono.TextMarginLeft = 3;
            this.txtTelefono.TextMarginTop = 1;
            this.txtTelefono.TextPlaceholder = "";
            this.txtTelefono.UseSystemPasswordChar = false;
            this.txtTelefono.WordWrap = true;
            // 
            // label4
            // 
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.label4.Location = new System.Drawing.Point(76, 241);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(108, 27);
            this.label4.TabIndex = 129;
            this.label4.Text = "Telefono";
            // 
            // txtDireccion
            // 
            this.txtDireccion.AcceptsReturn = false;
            this.txtDireccion.AcceptsTab = false;
            this.txtDireccion.AnimationSpeed = 200;
            this.txtDireccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDireccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDireccion.AutoSizeHeight = true;
            this.txtDireccion.BackColor = System.Drawing.Color.Transparent;
            this.txtDireccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDireccion.BackgroundImage")));
            this.txtDireccion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDireccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDireccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDireccion.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtDireccion.BorderRadius = 20;
            this.txtDireccion.BorderThickness = 1;
            this.txtDireccion.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDireccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDireccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDireccion.DefaultText = "";
            this.txtDireccion.FillColor = System.Drawing.Color.White;
            this.txtDireccion.HideSelection = true;
            this.txtDireccion.IconLeft = null;
            this.txtDireccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.IconPadding = 10;
            this.txtDireccion.IconRight = null;
            this.txtDireccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.Lines = new string[0];
            this.txtDireccion.Location = new System.Drawing.Point(78, 194);
            this.txtDireccion.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtDireccion.MaxLength = 32767;
            this.txtDireccion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDireccion.Modified = false;
            this.txtDireccion.Multiline = false;
            this.txtDireccion.Name = "txtDireccion";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDireccion.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Transparent;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnIdleState = stateProperties12;
            this.txtDireccion.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtDireccion.PasswordChar = '\0';
            this.txtDireccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDireccion.PlaceholderText = "";
            this.txtDireccion.ReadOnly = false;
            this.txtDireccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDireccion.SelectedText = "";
            this.txtDireccion.SelectionLength = 0;
            this.txtDireccion.SelectionStart = 0;
            this.txtDireccion.ShortcutsEnabled = true;
            this.txtDireccion.Size = new System.Drawing.Size(317, 34);
            this.txtDireccion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDireccion.TabIndex = 131;
            this.txtDireccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDireccion.TextMarginBottom = 0;
            this.txtDireccion.TextMarginLeft = 3;
            this.txtDireccion.TextMarginTop = 1;
            this.txtDireccion.TextPlaceholder = "";
            this.txtDireccion.UseSystemPasswordChar = false;
            this.txtDireccion.WordWrap = true;
            // 
            // label6
            // 
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.label6.Location = new System.Drawing.Point(76, 165);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(108, 27);
            this.label6.TabIndex = 130;
            this.label6.Text = "Direccion";
            // 
            // btnBuscarCliente
            // 
            this.btnBuscarCliente.AllowAnimations = true;
            this.btnBuscarCliente.AllowMouseEffects = true;
            this.btnBuscarCliente.AllowToggling = false;
            this.btnBuscarCliente.AnimationSpeed = 200;
            this.btnBuscarCliente.AutoGenerateColors = false;
            this.btnBuscarCliente.AutoRoundBorders = false;
            this.btnBuscarCliente.AutoSizeLeftIcon = true;
            this.btnBuscarCliente.AutoSizeRightIcon = true;
            this.btnBuscarCliente.BackColor = System.Drawing.Color.Transparent;
            this.btnBuscarCliente.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnBuscarCliente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBuscarCliente.BackgroundImage")));
            this.btnBuscarCliente.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuscarCliente.ButtonText = "Buscar";
            this.btnBuscarCliente.ButtonTextMarginLeft = 0;
            this.btnBuscarCliente.ColorContrastOnClick = 45;
            this.btnBuscarCliente.ColorContrastOnHover = 45;
            this.btnBuscarCliente.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnBuscarCliente.CustomizableEdges = borderEdges2;
            this.btnBuscarCliente.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBuscarCliente.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBuscarCliente.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBuscarCliente.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBuscarCliente.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.btnBuscarCliente.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBuscarCliente.ForeColor = System.Drawing.Color.White;
            this.btnBuscarCliente.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBuscarCliente.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBuscarCliente.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBuscarCliente.IconMarginLeft = 11;
            this.btnBuscarCliente.IconPadding = 10;
            this.btnBuscarCliente.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBuscarCliente.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBuscarCliente.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBuscarCliente.IconSize = 25;
            this.btnBuscarCliente.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnBuscarCliente.IdleBorderRadius = 20;
            this.btnBuscarCliente.IdleBorderThickness = 1;
            this.btnBuscarCliente.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnBuscarCliente.IdleIconLeftImage = null;
            this.btnBuscarCliente.IdleIconRightImage = null;
            this.btnBuscarCliente.IndicateFocus = false;
            this.btnBuscarCliente.Location = new System.Drawing.Point(410, 120);
            this.btnBuscarCliente.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnBuscarCliente.Name = "btnBuscarCliente";
            this.btnBuscarCliente.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBuscarCliente.OnDisabledState.BorderRadius = 20;
            this.btnBuscarCliente.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuscarCliente.OnDisabledState.BorderThickness = 1;
            this.btnBuscarCliente.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBuscarCliente.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBuscarCliente.OnDisabledState.IconLeftImage = null;
            this.btnBuscarCliente.OnDisabledState.IconRightImage = null;
            this.btnBuscarCliente.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnBuscarCliente.onHoverState.BorderRadius = 20;
            this.btnBuscarCliente.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuscarCliente.onHoverState.BorderThickness = 1;
            this.btnBuscarCliente.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnBuscarCliente.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnBuscarCliente.onHoverState.IconLeftImage = null;
            this.btnBuscarCliente.onHoverState.IconRightImage = null;
            this.btnBuscarCliente.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnBuscarCliente.OnIdleState.BorderRadius = 20;
            this.btnBuscarCliente.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuscarCliente.OnIdleState.BorderThickness = 1;
            this.btnBuscarCliente.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnBuscarCliente.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBuscarCliente.OnIdleState.IconLeftImage = null;
            this.btnBuscarCliente.OnIdleState.IconRightImage = null;
            this.btnBuscarCliente.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnBuscarCliente.OnPressedState.BorderRadius = 20;
            this.btnBuscarCliente.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnBuscarCliente.OnPressedState.BorderThickness = 1;
            this.btnBuscarCliente.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnBuscarCliente.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBuscarCliente.OnPressedState.IconLeftImage = null;
            this.btnBuscarCliente.OnPressedState.IconRightImage = null;
            this.btnBuscarCliente.Size = new System.Drawing.Size(127, 31);
            this.btnBuscarCliente.TabIndex = 152;
            this.btnBuscarCliente.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBuscarCliente.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBuscarCliente.TextMarginLeft = 0;
            this.btnBuscarCliente.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBuscarCliente.UseDefaultRadiusAndThickness = true;
            this.btnBuscarCliente.Click += new System.EventHandler(this.btnBuscarCliente_Click);
            // 
            // listBox1
            // 
            this.listBox1.FormattingEnabled = true;
            this.listBox1.ItemHeight = 16;
            this.listBox1.Location = new System.Drawing.Point(765, 204);
            this.listBox1.Margin = new System.Windows.Forms.Padding(4);
            this.listBox1.Name = "listBox1";
            this.listBox1.SelectionMode = System.Windows.Forms.SelectionMode.MultiSimple;
            this.listBox1.Size = new System.Drawing.Size(308, 100);
            this.listBox1.TabIndex = 213;
            // 
            // label20
            // 
            this.label20.AutoSize = true;
            this.label20.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label20.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.label20.Location = new System.Drawing.Point(760, 165);
            this.label20.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(77, 25);
            this.label20.TabIndex = 212;
            this.label20.Text = "Imagen";
            // 
            // btnImagen
            // 
            this.btnImagen.AllowAnimations = true;
            this.btnImagen.AllowMouseEffects = true;
            this.btnImagen.AllowToggling = false;
            this.btnImagen.AnimationSpeed = 200;
            this.btnImagen.AutoGenerateColors = false;
            this.btnImagen.AutoRoundBorders = false;
            this.btnImagen.AutoSizeLeftIcon = true;
            this.btnImagen.AutoSizeRightIcon = true;
            this.btnImagen.BackColor = System.Drawing.Color.Transparent;
            this.btnImagen.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnImagen.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnImagen.BackgroundImage")));
            this.btnImagen.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnImagen.ButtonText = "Subir";
            this.btnImagen.ButtonTextMarginLeft = 0;
            this.btnImagen.ColorContrastOnClick = 45;
            this.btnImagen.ColorContrastOnHover = 45;
            this.btnImagen.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnImagen.CustomizableEdges = borderEdges3;
            this.btnImagen.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnImagen.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImagen.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImagen.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImagen.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Hover;
            this.btnImagen.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnImagen.ForeColor = System.Drawing.Color.White;
            this.btnImagen.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnImagen.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnImagen.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnImagen.IconMarginLeft = 11;
            this.btnImagen.IconPadding = 10;
            this.btnImagen.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnImagen.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnImagen.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnImagen.IconSize = 25;
            this.btnImagen.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnImagen.IdleBorderRadius = 20;
            this.btnImagen.IdleBorderThickness = 1;
            this.btnImagen.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnImagen.IdleIconLeftImage = null;
            this.btnImagen.IdleIconRightImage = null;
            this.btnImagen.IndicateFocus = false;
            this.btnImagen.Location = new System.Drawing.Point(904, 162);
            this.btnImagen.Margin = new System.Windows.Forms.Padding(4);
            this.btnImagen.Name = "btnImagen";
            this.btnImagen.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnImagen.OnDisabledState.BorderRadius = 20;
            this.btnImagen.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnImagen.OnDisabledState.BorderThickness = 1;
            this.btnImagen.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnImagen.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnImagen.OnDisabledState.IconLeftImage = null;
            this.btnImagen.OnDisabledState.IconRightImage = null;
            this.btnImagen.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnImagen.onHoverState.BorderRadius = 20;
            this.btnImagen.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnImagen.onHoverState.BorderThickness = 1;
            this.btnImagen.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnImagen.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnImagen.onHoverState.IconLeftImage = null;
            this.btnImagen.onHoverState.IconRightImage = null;
            this.btnImagen.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnImagen.OnIdleState.BorderRadius = 20;
            this.btnImagen.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnImagen.OnIdleState.BorderThickness = 1;
            this.btnImagen.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnImagen.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnImagen.OnIdleState.IconLeftImage = null;
            this.btnImagen.OnIdleState.IconRightImage = null;
            this.btnImagen.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnImagen.OnPressedState.BorderRadius = 20;
            this.btnImagen.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnImagen.OnPressedState.BorderThickness = 1;
            this.btnImagen.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnImagen.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnImagen.OnPressedState.IconLeftImage = null;
            this.btnImagen.OnPressedState.IconRightImage = null;
            this.btnImagen.Size = new System.Drawing.Size(169, 38);
            this.btnImagen.TabIndex = 211;
            this.btnImagen.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnImagen.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnImagen.TextMarginLeft = 0;
            this.btnImagen.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnImagen.UseDefaultRadiusAndThickness = true;
            this.btnImagen.Click += new System.EventHandler(this.btnImagen_Click);
            // 
            // openFileDialog1
            // 
            this.openFileDialog1.FileName = "openFileDialog1";
            // 
            // txtFechaEntrada
            // 
            this.txtFechaEntrada.AcceptsReturn = false;
            this.txtFechaEntrada.AcceptsTab = false;
            this.txtFechaEntrada.AnimationSpeed = 200;
            this.txtFechaEntrada.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFechaEntrada.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFechaEntrada.AutoSizeHeight = true;
            this.txtFechaEntrada.BackColor = System.Drawing.Color.Transparent;
            this.txtFechaEntrada.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFechaEntrada.BackgroundImage")));
            this.txtFechaEntrada.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFechaEntrada.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFechaEntrada.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFechaEntrada.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtFechaEntrada.BorderRadius = 20;
            this.txtFechaEntrada.BorderThickness = 1;
            this.txtFechaEntrada.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtFechaEntrada.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFechaEntrada.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFechaEntrada.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFechaEntrada.DefaultText = "";
            this.txtFechaEntrada.FillColor = System.Drawing.Color.White;
            this.txtFechaEntrada.HideSelection = true;
            this.txtFechaEntrada.IconLeft = null;
            this.txtFechaEntrada.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFechaEntrada.IconPadding = 10;
            this.txtFechaEntrada.IconRight = null;
            this.txtFechaEntrada.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFechaEntrada.Lines = new string[0];
            this.txtFechaEntrada.Location = new System.Drawing.Point(413, 194);
            this.txtFechaEntrada.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtFechaEntrada.MaxLength = 32767;
            this.txtFechaEntrada.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFechaEntrada.Modified = false;
            this.txtFechaEntrada.Multiline = false;
            this.txtFechaEntrada.Name = "txtFechaEntrada";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFechaEntrada.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFechaEntrada.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFechaEntrada.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Transparent;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFechaEntrada.OnIdleState = stateProperties16;
            this.txtFechaEntrada.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtFechaEntrada.PasswordChar = '\0';
            this.txtFechaEntrada.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFechaEntrada.PlaceholderText = "";
            this.txtFechaEntrada.ReadOnly = false;
            this.txtFechaEntrada.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFechaEntrada.SelectedText = "";
            this.txtFechaEntrada.SelectionLength = 0;
            this.txtFechaEntrada.SelectionStart = 0;
            this.txtFechaEntrada.ShortcutsEnabled = true;
            this.txtFechaEntrada.Size = new System.Drawing.Size(317, 34);
            this.txtFechaEntrada.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFechaEntrada.TabIndex = 214;
            this.txtFechaEntrada.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFechaEntrada.TextMarginBottom = 0;
            this.txtFechaEntrada.TextMarginLeft = 3;
            this.txtFechaEntrada.TextMarginTop = 1;
            this.txtFechaEntrada.TextPlaceholder = "";
            this.txtFechaEntrada.UseSystemPasswordChar = false;
            this.txtFechaEntrada.WordWrap = true;
            // 
            // label1
            // 
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.label1.Location = new System.Drawing.Point(411, 165);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(209, 27);
            this.label1.TabIndex = 215;
            this.label1.Text = "Fecha de entrada";
            // 
            // txtFechaSalida
            // 
            this.txtFechaSalida.AcceptsReturn = false;
            this.txtFechaSalida.AcceptsTab = false;
            this.txtFechaSalida.AnimationSpeed = 200;
            this.txtFechaSalida.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFechaSalida.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFechaSalida.AutoSizeHeight = true;
            this.txtFechaSalida.BackColor = System.Drawing.Color.Transparent;
            this.txtFechaSalida.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFechaSalida.BackgroundImage")));
            this.txtFechaSalida.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFechaSalida.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFechaSalida.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFechaSalida.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtFechaSalida.BorderRadius = 20;
            this.txtFechaSalida.BorderThickness = 1;
            this.txtFechaSalida.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtFechaSalida.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFechaSalida.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFechaSalida.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFechaSalida.DefaultText = "";
            this.txtFechaSalida.FillColor = System.Drawing.Color.White;
            this.txtFechaSalida.HideSelection = true;
            this.txtFechaSalida.IconLeft = null;
            this.txtFechaSalida.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFechaSalida.IconPadding = 10;
            this.txtFechaSalida.IconRight = null;
            this.txtFechaSalida.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFechaSalida.Lines = new string[0];
            this.txtFechaSalida.Location = new System.Drawing.Point(416, 270);
            this.txtFechaSalida.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtFechaSalida.MaxLength = 32767;
            this.txtFechaSalida.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFechaSalida.Modified = false;
            this.txtFechaSalida.Multiline = false;
            this.txtFechaSalida.Name = "txtFechaSalida";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFechaSalida.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFechaSalida.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFechaSalida.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Transparent;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFechaSalida.OnIdleState = stateProperties20;
            this.txtFechaSalida.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtFechaSalida.PasswordChar = '\0';
            this.txtFechaSalida.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFechaSalida.PlaceholderText = "";
            this.txtFechaSalida.ReadOnly = false;
            this.txtFechaSalida.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFechaSalida.SelectedText = "";
            this.txtFechaSalida.SelectionLength = 0;
            this.txtFechaSalida.SelectionStart = 0;
            this.txtFechaSalida.ShortcutsEnabled = true;
            this.txtFechaSalida.Size = new System.Drawing.Size(317, 34);
            this.txtFechaSalida.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFechaSalida.TabIndex = 216;
            this.txtFechaSalida.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFechaSalida.TextMarginBottom = 0;
            this.txtFechaSalida.TextMarginLeft = 3;
            this.txtFechaSalida.TextMarginTop = 1;
            this.txtFechaSalida.TextPlaceholder = "";
            this.txtFechaSalida.UseSystemPasswordChar = false;
            this.txtFechaSalida.WordWrap = true;
            // 
            // label2
            // 
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.label2.Location = new System.Drawing.Point(414, 241);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(209, 27);
            this.label2.TabIndex = 217;
            this.label2.Text = "Fecha de salida";
            // 
            // txtFiltroNCF
            // 
            this.txtFiltroNCF.AcceptsReturn = false;
            this.txtFiltroNCF.AcceptsTab = false;
            this.txtFiltroNCF.AnimationSpeed = 200;
            this.txtFiltroNCF.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFiltroNCF.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFiltroNCF.AutoSizeHeight = true;
            this.txtFiltroNCF.BackColor = System.Drawing.Color.Transparent;
            this.txtFiltroNCF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFiltroNCF.BackgroundImage")));
            this.txtFiltroNCF.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFiltroNCF.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFiltroNCF.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFiltroNCF.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtFiltroNCF.BorderRadius = 15;
            this.txtFiltroNCF.BorderThickness = 1;
            this.txtFiltroNCF.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtFiltroNCF.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFiltroNCF.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltroNCF.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFiltroNCF.DefaultText = "";
            this.txtFiltroNCF.FillColor = System.Drawing.Color.White;
            this.txtFiltroNCF.HideSelection = true;
            this.txtFiltroNCF.IconLeft = null;
            this.txtFiltroNCF.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltroNCF.IconPadding = 10;
            this.txtFiltroNCF.IconRight = null;
            this.txtFiltroNCF.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltroNCF.Lines = new string[0];
            this.txtFiltroNCF.Location = new System.Drawing.Point(78, 384);
            this.txtFiltroNCF.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtFiltroNCF.MaxLength = 32767;
            this.txtFiltroNCF.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFiltroNCF.Modified = false;
            this.txtFiltroNCF.Multiline = false;
            this.txtFiltroNCF.Name = "txtFiltroNCF";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltroNCF.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFiltroNCF.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltroNCF.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Transparent;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltroNCF.OnIdleState = stateProperties24;
            this.txtFiltroNCF.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtFiltroNCF.PasswordChar = '\0';
            this.txtFiltroNCF.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFiltroNCF.PlaceholderText = "Buscar";
            this.txtFiltroNCF.ReadOnly = false;
            this.txtFiltroNCF.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFiltroNCF.SelectedText = "";
            this.txtFiltroNCF.SelectionLength = 0;
            this.txtFiltroNCF.SelectionStart = 0;
            this.txtFiltroNCF.ShortcutsEnabled = true;
            this.txtFiltroNCF.Size = new System.Drawing.Size(381, 46);
            this.txtFiltroNCF.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFiltroNCF.TabIndex = 218;
            this.txtFiltroNCF.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFiltroNCF.TextMarginBottom = 0;
            this.txtFiltroNCF.TextMarginLeft = 3;
            this.txtFiltroNCF.TextMarginTop = 1;
            this.txtFiltroNCF.TextPlaceholder = "Buscar";
            this.txtFiltroNCF.UseSystemPasswordChar = false;
            this.txtFiltroNCF.WordWrap = true;
            this.txtFiltroNCF.TextChanged += new System.EventHandler(this.txtFiltroNCF_TextChanged);
            // 
            // Fabricacion
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1604, 738);
            this.Controls.Add(this.txtFiltroNCF);
            this.Controls.Add(this.txtFechaSalida);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.txtFechaEntrada);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.listBox1);
            this.Controls.Add(this.label20);
            this.Controls.Add(this.btnImagen);
            this.Controls.Add(this.btnBuscarCliente);
            this.Controls.Add(this.txtDireccion);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.txtTelefono);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.txtCliente_NombreR);
            this.Controls.Add(this.lblNombre);
            this.Controls.Add(this.bunifuVScrollBar2);
            this.Controls.Add(this.dtaFacturas);
            this.Controls.Add(this.btnGuardarClienteR);
            this.Controls.Add(this.bunifuLabel2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Fabricacion";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Fabricacion";
            this.Load += new System.EventHandler(this.Fabricacion_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dtaFacturas)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuVScrollBar bunifuVScrollBar2;
        private Bunifu.UI.WinForms.BunifuDataGridView dtaFacturas;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnGuardarClienteR;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox txtCliente_NombreR;
        private System.Windows.Forms.Label lblNombre;
        private Bunifu.UI.WinForms.BunifuTextBox txtTelefono;
        private System.Windows.Forms.Label label4;
        private Bunifu.UI.WinForms.BunifuTextBox txtDireccion;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnBuscarCliente;
        private System.Windows.Forms.ListBox listBox1;
        private System.Windows.Forms.Label label20;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnImagen;
        private System.Windows.Forms.OpenFileDialog openFileDialog1;
        private Bunifu.UI.WinForms.BunifuTextBox txtFechaEntrada;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox txtFechaSalida;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox txtFiltroNCF;
    }
}