namespace Capa_P
{
    partial class Layout
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Layout));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.btnUsuario = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnUsuarios = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnMateriales = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnNCF = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnFacturas = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnVentas = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnCliente = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnDashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuPanel4 = new Bunifu.UI.WinForms.BunifuPanel();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.tableLayoutPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnUsuario
            // 
            this.btnUsuario.AllowAnimations = true;
            this.btnUsuario.AllowMouseEffects = true;
            this.btnUsuario.AllowToggling = false;
            this.btnUsuario.AnimationSpeed = 200;
            this.btnUsuario.AutoGenerateColors = false;
            this.btnUsuario.AutoRoundBorders = false;
            this.btnUsuario.AutoSizeLeftIcon = true;
            this.btnUsuario.AutoSizeRightIcon = true;
            this.btnUsuario.BackColor = System.Drawing.Color.Transparent;
            this.btnUsuario.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnUsuario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUsuario.BackgroundImage")));
            this.btnUsuario.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUsuario.ButtonText = "Usuarios";
            this.btnUsuario.ButtonTextMarginLeft = 0;
            this.btnUsuario.ColorContrastOnClick = 45;
            this.btnUsuario.ColorContrastOnHover = 45;
            this.btnUsuario.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnUsuario.CustomizableEdges = borderEdges1;
            this.btnUsuario.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUsuario.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUsuario.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUsuario.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUsuario.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnUsuario.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUsuario.ForeColor = System.Drawing.Color.White;
            this.btnUsuario.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUsuario.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUsuario.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.btnUsuario.IconMarginLeft = 11;
            this.btnUsuario.IconPadding = 10;
            this.btnUsuario.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUsuario.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUsuario.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUsuario.IconSize = 30;
            this.btnUsuario.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnUsuario.IdleBorderRadius = 1;
            this.btnUsuario.IdleBorderThickness = 1;
            this.btnUsuario.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnUsuario.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnUsuario.IdleIconLeftImage")));
            this.btnUsuario.IdleIconRightImage = null;
            this.btnUsuario.IndicateFocus = false;
            this.btnUsuario.Location = new System.Drawing.Point(707, 647);
            this.btnUsuario.Margin = new System.Windows.Forms.Padding(5, 2, 3, 2);
            this.btnUsuario.Name = "btnUsuario";
            this.btnUsuario.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUsuario.OnDisabledState.BorderRadius = 1;
            this.btnUsuario.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUsuario.OnDisabledState.BorderThickness = 1;
            this.btnUsuario.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUsuario.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUsuario.OnDisabledState.IconLeftImage = null;
            this.btnUsuario.OnDisabledState.IconRightImage = null;
            this.btnUsuario.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnUsuario.onHoverState.BorderRadius = 1;
            this.btnUsuario.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUsuario.onHoverState.BorderThickness = 1;
            this.btnUsuario.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnUsuario.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUsuario.onHoverState.IconLeftImage = null;
            this.btnUsuario.onHoverState.IconRightImage = null;
            this.btnUsuario.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnUsuario.OnIdleState.BorderRadius = 1;
            this.btnUsuario.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUsuario.OnIdleState.BorderThickness = 1;
            this.btnUsuario.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnUsuario.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUsuario.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnUsuario.OnIdleState.IconLeftImage")));
            this.btnUsuario.OnIdleState.IconRightImage = null;
            this.btnUsuario.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnUsuario.OnPressedState.BorderRadius = 1;
            this.btnUsuario.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUsuario.OnPressedState.BorderThickness = 1;
            this.btnUsuario.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnUsuario.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUsuario.OnPressedState.IconLeftImage = null;
            this.btnUsuario.OnPressedState.IconRightImage = null;
            this.btnUsuario.Size = new System.Drawing.Size(293, 43);
            this.btnUsuario.TabIndex = 18;
            this.btnUsuario.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUsuario.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUsuario.TextMarginLeft = 0;
            this.btnUsuario.TextPadding = new System.Windows.Forms.Padding(56, 4, 0, 2);
            this.btnUsuario.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnUsuarios);
            this.bunifuPanel1.Controls.Add(this.btnMateriales);
            this.bunifuPanel1.Controls.Add(this.btnNCF);
            this.bunifuPanel1.Controls.Add(this.btnFacturas);
            this.bunifuPanel1.Controls.Add(this.btnVentas);
            this.bunifuPanel1.Controls.Add(this.btnCliente);
            this.bunifuPanel1.Controls.Add(this.btnDashboard);
            this.bunifuPanel1.Controls.Add(this.pictureBox1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(320, 786);
            this.bunifuPanel1.TabIndex = 19;
            // 
            // btnUsuarios
            // 
            this.btnUsuarios.AllowAnimations = true;
            this.btnUsuarios.AllowMouseEffects = true;
            this.btnUsuarios.AllowToggling = false;
            this.btnUsuarios.AnimationSpeed = 200;
            this.btnUsuarios.AutoGenerateColors = false;
            this.btnUsuarios.AutoRoundBorders = false;
            this.btnUsuarios.AutoSizeLeftIcon = true;
            this.btnUsuarios.AutoSizeRightIcon = true;
            this.btnUsuarios.BackColor = System.Drawing.Color.Transparent;
            this.btnUsuarios.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnUsuarios.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUsuarios.BackgroundImage")));
            this.btnUsuarios.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUsuarios.ButtonText = "Usuarios";
            this.btnUsuarios.ButtonTextMarginLeft = 0;
            this.btnUsuarios.ColorContrastOnClick = 45;
            this.btnUsuarios.ColorContrastOnHover = 45;
            this.btnUsuarios.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnUsuarios.CustomizableEdges = borderEdges2;
            this.btnUsuarios.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUsuarios.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUsuarios.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUsuarios.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUsuarios.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnUsuarios.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUsuarios.ForeColor = System.Drawing.Color.White;
            this.btnUsuarios.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUsuarios.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUsuarios.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.btnUsuarios.IconMarginLeft = 11;
            this.btnUsuarios.IconPadding = 10;
            this.btnUsuarios.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUsuarios.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUsuarios.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUsuarios.IconSize = 30;
            this.btnUsuarios.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnUsuarios.IdleBorderRadius = 1;
            this.btnUsuarios.IdleBorderThickness = 1;
            this.btnUsuarios.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnUsuarios.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnUsuarios.IdleIconLeftImage")));
            this.btnUsuarios.IdleIconRightImage = null;
            this.btnUsuarios.IndicateFocus = false;
            this.btnUsuarios.Location = new System.Drawing.Point(8, 526);
            this.btnUsuarios.Margin = new System.Windows.Forms.Padding(5, 2, 3, 2);
            this.btnUsuarios.Name = "btnUsuarios";
            this.btnUsuarios.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUsuarios.OnDisabledState.BorderRadius = 1;
            this.btnUsuarios.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUsuarios.OnDisabledState.BorderThickness = 1;
            this.btnUsuarios.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUsuarios.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUsuarios.OnDisabledState.IconLeftImage = null;
            this.btnUsuarios.OnDisabledState.IconRightImage = null;
            this.btnUsuarios.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnUsuarios.onHoverState.BorderRadius = 1;
            this.btnUsuarios.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUsuarios.onHoverState.BorderThickness = 1;
            this.btnUsuarios.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnUsuarios.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUsuarios.onHoverState.IconLeftImage = null;
            this.btnUsuarios.onHoverState.IconRightImage = null;
            this.btnUsuarios.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnUsuarios.OnIdleState.BorderRadius = 1;
            this.btnUsuarios.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUsuarios.OnIdleState.BorderThickness = 1;
            this.btnUsuarios.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnUsuarios.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUsuarios.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnUsuarios.OnIdleState.IconLeftImage")));
            this.btnUsuarios.OnIdleState.IconRightImage = null;
            this.btnUsuarios.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnUsuarios.OnPressedState.BorderRadius = 1;
            this.btnUsuarios.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnUsuarios.OnPressedState.BorderThickness = 1;
            this.btnUsuarios.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnUsuarios.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUsuarios.OnPressedState.IconLeftImage = null;
            this.btnUsuarios.OnPressedState.IconRightImage = null;
            this.btnUsuarios.Size = new System.Drawing.Size(267, 43);
            this.btnUsuarios.TabIndex = 10;
            this.btnUsuarios.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUsuarios.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUsuarios.TextMarginLeft = 0;
            this.btnUsuarios.TextPadding = new System.Windows.Forms.Padding(56, 4, 0, 2);
            this.btnUsuarios.UseDefaultRadiusAndThickness = true;
            this.btnUsuarios.Click += new System.EventHandler(this.btnUsuarios_Click);
            // 
            // btnMateriales
            // 
            this.btnMateriales.AllowAnimations = true;
            this.btnMateriales.AllowMouseEffects = true;
            this.btnMateriales.AllowToggling = false;
            this.btnMateriales.AnimationSpeed = 200;
            this.btnMateriales.AutoGenerateColors = false;
            this.btnMateriales.AutoRoundBorders = false;
            this.btnMateriales.AutoSizeLeftIcon = true;
            this.btnMateriales.AutoSizeRightIcon = true;
            this.btnMateriales.BackColor = System.Drawing.Color.Transparent;
            this.btnMateriales.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnMateriales.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnMateriales.BackgroundImage")));
            this.btnMateriales.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnMateriales.ButtonText = "Ficha de Fabricacion";
            this.btnMateriales.ButtonTextMarginLeft = 0;
            this.btnMateriales.ColorContrastOnClick = 45;
            this.btnMateriales.ColorContrastOnHover = 45;
            this.btnMateriales.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnMateriales.CustomizableEdges = borderEdges3;
            this.btnMateriales.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMateriales.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMateriales.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMateriales.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMateriales.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnMateriales.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnMateriales.ForeColor = System.Drawing.Color.White;
            this.btnMateriales.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMateriales.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnMateriales.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.btnMateriales.IconMarginLeft = 11;
            this.btnMateriales.IconPadding = 10;
            this.btnMateriales.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnMateriales.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnMateriales.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnMateriales.IconSize = 30;
            this.btnMateriales.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnMateriales.IdleBorderRadius = 1;
            this.btnMateriales.IdleBorderThickness = 1;
            this.btnMateriales.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnMateriales.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnMateriales.IdleIconLeftImage")));
            this.btnMateriales.IdleIconRightImage = null;
            this.btnMateriales.IndicateFocus = false;
            this.btnMateriales.Location = new System.Drawing.Point(8, 466);
            this.btnMateriales.Margin = new System.Windows.Forms.Padding(5, 2, 3, 2);
            this.btnMateriales.Name = "btnMateriales";
            this.btnMateriales.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMateriales.OnDisabledState.BorderRadius = 1;
            this.btnMateriales.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnMateriales.OnDisabledState.BorderThickness = 1;
            this.btnMateriales.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMateriales.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMateriales.OnDisabledState.IconLeftImage = null;
            this.btnMateriales.OnDisabledState.IconRightImage = null;
            this.btnMateriales.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnMateriales.onHoverState.BorderRadius = 1;
            this.btnMateriales.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnMateriales.onHoverState.BorderThickness = 1;
            this.btnMateriales.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnMateriales.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnMateriales.onHoverState.IconLeftImage = null;
            this.btnMateriales.onHoverState.IconRightImage = null;
            this.btnMateriales.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnMateriales.OnIdleState.BorderRadius = 1;
            this.btnMateriales.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnMateriales.OnIdleState.BorderThickness = 1;
            this.btnMateriales.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnMateriales.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnMateriales.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnMateriales.OnIdleState.IconLeftImage")));
            this.btnMateriales.OnIdleState.IconRightImage = null;
            this.btnMateriales.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnMateriales.OnPressedState.BorderRadius = 1;
            this.btnMateriales.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnMateriales.OnPressedState.BorderThickness = 1;
            this.btnMateriales.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnMateriales.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnMateriales.OnPressedState.IconLeftImage = null;
            this.btnMateriales.OnPressedState.IconRightImage = null;
            this.btnMateriales.Size = new System.Drawing.Size(267, 43);
            this.btnMateriales.TabIndex = 9;
            this.btnMateriales.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMateriales.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnMateriales.TextMarginLeft = 0;
            this.btnMateriales.TextPadding = new System.Windows.Forms.Padding(56, 4, 0, 2);
            this.btnMateriales.UseDefaultRadiusAndThickness = true;
            this.btnMateriales.Click += new System.EventHandler(this.btnMateriales_Click);
            // 
            // btnNCF
            // 
            this.btnNCF.AllowAnimations = true;
            this.btnNCF.AllowMouseEffects = true;
            this.btnNCF.AllowToggling = false;
            this.btnNCF.AnimationSpeed = 200;
            this.btnNCF.AutoGenerateColors = false;
            this.btnNCF.AutoRoundBorders = false;
            this.btnNCF.AutoSizeLeftIcon = true;
            this.btnNCF.AutoSizeRightIcon = true;
            this.btnNCF.BackColor = System.Drawing.Color.Transparent;
            this.btnNCF.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnNCF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnNCF.BackgroundImage")));
            this.btnNCF.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnNCF.ButtonText = "NCF";
            this.btnNCF.ButtonTextMarginLeft = 0;
            this.btnNCF.ColorContrastOnClick = 45;
            this.btnNCF.ColorContrastOnHover = 45;
            this.btnNCF.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnNCF.CustomizableEdges = borderEdges4;
            this.btnNCF.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnNCF.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNCF.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNCF.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNCF.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnNCF.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnNCF.ForeColor = System.Drawing.Color.White;
            this.btnNCF.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNCF.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnNCF.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.btnNCF.IconMarginLeft = 11;
            this.btnNCF.IconPadding = 10;
            this.btnNCF.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnNCF.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnNCF.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnNCF.IconSize = 30;
            this.btnNCF.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnNCF.IdleBorderRadius = 1;
            this.btnNCF.IdleBorderThickness = 1;
            this.btnNCF.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnNCF.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnNCF.IdleIconLeftImage")));
            this.btnNCF.IdleIconRightImage = null;
            this.btnNCF.IndicateFocus = false;
            this.btnNCF.Location = new System.Drawing.Point(8, 406);
            this.btnNCF.Margin = new System.Windows.Forms.Padding(5, 2, 3, 2);
            this.btnNCF.Name = "btnNCF";
            this.btnNCF.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnNCF.OnDisabledState.BorderRadius = 1;
            this.btnNCF.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnNCF.OnDisabledState.BorderThickness = 1;
            this.btnNCF.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnNCF.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnNCF.OnDisabledState.IconLeftImage = null;
            this.btnNCF.OnDisabledState.IconRightImage = null;
            this.btnNCF.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnNCF.onHoverState.BorderRadius = 1;
            this.btnNCF.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnNCF.onHoverState.BorderThickness = 1;
            this.btnNCF.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnNCF.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnNCF.onHoverState.IconLeftImage = null;
            this.btnNCF.onHoverState.IconRightImage = null;
            this.btnNCF.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnNCF.OnIdleState.BorderRadius = 1;
            this.btnNCF.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnNCF.OnIdleState.BorderThickness = 1;
            this.btnNCF.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnNCF.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnNCF.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnNCF.OnIdleState.IconLeftImage")));
            this.btnNCF.OnIdleState.IconRightImage = null;
            this.btnNCF.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnNCF.OnPressedState.BorderRadius = 1;
            this.btnNCF.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnNCF.OnPressedState.BorderThickness = 1;
            this.btnNCF.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnNCF.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnNCF.OnPressedState.IconLeftImage = null;
            this.btnNCF.OnPressedState.IconRightImage = null;
            this.btnNCF.Size = new System.Drawing.Size(267, 43);
            this.btnNCF.TabIndex = 8;
            this.btnNCF.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnNCF.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnNCF.TextMarginLeft = 0;
            this.btnNCF.TextPadding = new System.Windows.Forms.Padding(56, 4, 0, 2);
            this.btnNCF.UseDefaultRadiusAndThickness = true;
            this.btnNCF.Click += new System.EventHandler(this.btnNCF_Click);
            // 
            // btnFacturas
            // 
            this.btnFacturas.AllowAnimations = true;
            this.btnFacturas.AllowMouseEffects = true;
            this.btnFacturas.AllowToggling = false;
            this.btnFacturas.AnimationSpeed = 200;
            this.btnFacturas.AutoGenerateColors = false;
            this.btnFacturas.AutoRoundBorders = false;
            this.btnFacturas.AutoSizeLeftIcon = true;
            this.btnFacturas.AutoSizeRightIcon = true;
            this.btnFacturas.BackColor = System.Drawing.Color.Transparent;
            this.btnFacturas.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnFacturas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFacturas.BackgroundImage")));
            this.btnFacturas.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFacturas.ButtonText = "Historial";
            this.btnFacturas.ButtonTextMarginLeft = 0;
            this.btnFacturas.ColorContrastOnClick = 45;
            this.btnFacturas.ColorContrastOnHover = 45;
            this.btnFacturas.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnFacturas.CustomizableEdges = borderEdges5;
            this.btnFacturas.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFacturas.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFacturas.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFacturas.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFacturas.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnFacturas.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnFacturas.ForeColor = System.Drawing.Color.White;
            this.btnFacturas.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFacturas.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFacturas.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.btnFacturas.IconMarginLeft = 11;
            this.btnFacturas.IconPadding = 10;
            this.btnFacturas.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFacturas.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFacturas.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFacturas.IconSize = 30;
            this.btnFacturas.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnFacturas.IdleBorderRadius = 1;
            this.btnFacturas.IdleBorderThickness = 1;
            this.btnFacturas.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnFacturas.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnFacturas.IdleIconLeftImage")));
            this.btnFacturas.IdleIconRightImage = null;
            this.btnFacturas.IndicateFocus = false;
            this.btnFacturas.Location = new System.Drawing.Point(8, 346);
            this.btnFacturas.Margin = new System.Windows.Forms.Padding(5, 2, 3, 2);
            this.btnFacturas.Name = "btnFacturas";
            this.btnFacturas.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFacturas.OnDisabledState.BorderRadius = 1;
            this.btnFacturas.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFacturas.OnDisabledState.BorderThickness = 1;
            this.btnFacturas.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFacturas.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFacturas.OnDisabledState.IconLeftImage = null;
            this.btnFacturas.OnDisabledState.IconRightImage = null;
            this.btnFacturas.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnFacturas.onHoverState.BorderRadius = 1;
            this.btnFacturas.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFacturas.onHoverState.BorderThickness = 1;
            this.btnFacturas.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnFacturas.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnFacturas.onHoverState.IconLeftImage = null;
            this.btnFacturas.onHoverState.IconRightImage = null;
            this.btnFacturas.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnFacturas.OnIdleState.BorderRadius = 1;
            this.btnFacturas.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFacturas.OnIdleState.BorderThickness = 1;
            this.btnFacturas.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnFacturas.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnFacturas.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnFacturas.OnIdleState.IconLeftImage")));
            this.btnFacturas.OnIdleState.IconRightImage = null;
            this.btnFacturas.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnFacturas.OnPressedState.BorderRadius = 1;
            this.btnFacturas.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFacturas.OnPressedState.BorderThickness = 1;
            this.btnFacturas.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnFacturas.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFacturas.OnPressedState.IconLeftImage = null;
            this.btnFacturas.OnPressedState.IconRightImage = null;
            this.btnFacturas.Size = new System.Drawing.Size(267, 43);
            this.btnFacturas.TabIndex = 7;
            this.btnFacturas.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFacturas.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFacturas.TextMarginLeft = 0;
            this.btnFacturas.TextPadding = new System.Windows.Forms.Padding(56, 4, 0, 2);
            this.btnFacturas.UseDefaultRadiusAndThickness = true;
            this.btnFacturas.Click += new System.EventHandler(this.btnFacturas_Click);
            // 
            // btnVentas
            // 
            this.btnVentas.AllowAnimations = true;
            this.btnVentas.AllowMouseEffects = true;
            this.btnVentas.AllowToggling = false;
            this.btnVentas.AnimationSpeed = 200;
            this.btnVentas.AutoGenerateColors = false;
            this.btnVentas.AutoRoundBorders = false;
            this.btnVentas.AutoSizeLeftIcon = true;
            this.btnVentas.AutoSizeRightIcon = true;
            this.btnVentas.BackColor = System.Drawing.Color.Transparent;
            this.btnVentas.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnVentas.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVentas.BackgroundImage")));
            this.btnVentas.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVentas.ButtonText = "Ventas";
            this.btnVentas.ButtonTextMarginLeft = 0;
            this.btnVentas.ColorContrastOnClick = 45;
            this.btnVentas.ColorContrastOnHover = 45;
            this.btnVentas.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnVentas.CustomizableEdges = borderEdges6;
            this.btnVentas.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVentas.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVentas.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVentas.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVentas.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnVentas.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnVentas.ForeColor = System.Drawing.Color.White;
            this.btnVentas.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVentas.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnVentas.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.btnVentas.IconMarginLeft = 11;
            this.btnVentas.IconPadding = 10;
            this.btnVentas.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVentas.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnVentas.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnVentas.IconSize = 30;
            this.btnVentas.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnVentas.IdleBorderRadius = 1;
            this.btnVentas.IdleBorderThickness = 1;
            this.btnVentas.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnVentas.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnVentas.IdleIconLeftImage")));
            this.btnVentas.IdleIconRightImage = null;
            this.btnVentas.IndicateFocus = false;
            this.btnVentas.Location = new System.Drawing.Point(8, 286);
            this.btnVentas.Margin = new System.Windows.Forms.Padding(5, 2, 3, 2);
            this.btnVentas.Name = "btnVentas";
            this.btnVentas.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVentas.OnDisabledState.BorderRadius = 1;
            this.btnVentas.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVentas.OnDisabledState.BorderThickness = 1;
            this.btnVentas.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVentas.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVentas.OnDisabledState.IconLeftImage = null;
            this.btnVentas.OnDisabledState.IconRightImage = null;
            this.btnVentas.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnVentas.onHoverState.BorderRadius = 1;
            this.btnVentas.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVentas.onHoverState.BorderThickness = 1;
            this.btnVentas.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnVentas.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnVentas.onHoverState.IconLeftImage = null;
            this.btnVentas.onHoverState.IconRightImage = null;
            this.btnVentas.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnVentas.OnIdleState.BorderRadius = 1;
            this.btnVentas.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVentas.OnIdleState.BorderThickness = 1;
            this.btnVentas.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnVentas.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnVentas.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnVentas.OnIdleState.IconLeftImage")));
            this.btnVentas.OnIdleState.IconRightImage = null;
            this.btnVentas.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnVentas.OnPressedState.BorderRadius = 1;
            this.btnVentas.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnVentas.OnPressedState.BorderThickness = 1;
            this.btnVentas.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnVentas.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnVentas.OnPressedState.IconLeftImage = null;
            this.btnVentas.OnPressedState.IconRightImage = null;
            this.btnVentas.Size = new System.Drawing.Size(267, 43);
            this.btnVentas.TabIndex = 6;
            this.btnVentas.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVentas.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnVentas.TextMarginLeft = 0;
            this.btnVentas.TextPadding = new System.Windows.Forms.Padding(56, 4, 0, 2);
            this.btnVentas.UseDefaultRadiusAndThickness = true;
            this.btnVentas.Click += new System.EventHandler(this.bunifuButton25_Click);
            // 
            // btnCliente
            // 
            this.btnCliente.AllowAnimations = true;
            this.btnCliente.AllowMouseEffects = true;
            this.btnCliente.AllowToggling = false;
            this.btnCliente.AnimationSpeed = 200;
            this.btnCliente.AutoGenerateColors = false;
            this.btnCliente.AutoRoundBorders = false;
            this.btnCliente.AutoSizeLeftIcon = true;
            this.btnCliente.AutoSizeRightIcon = true;
            this.btnCliente.BackColor = System.Drawing.Color.Transparent;
            this.btnCliente.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnCliente.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCliente.BackgroundImage")));
            this.btnCliente.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCliente.ButtonText = "Cliente";
            this.btnCliente.ButtonTextMarginLeft = 0;
            this.btnCliente.ColorContrastOnClick = 45;
            this.btnCliente.ColorContrastOnHover = 45;
            this.btnCliente.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnCliente.CustomizableEdges = borderEdges7;
            this.btnCliente.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCliente.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCliente.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCliente.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCliente.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnCliente.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCliente.ForeColor = System.Drawing.Color.White;
            this.btnCliente.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCliente.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCliente.IconLeftPadding = new System.Windows.Forms.Padding(30, 3, 3, 3);
            this.btnCliente.IconMarginLeft = 11;
            this.btnCliente.IconPadding = 10;
            this.btnCliente.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCliente.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCliente.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCliente.IconSize = 30;
            this.btnCliente.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnCliente.IdleBorderRadius = 1;
            this.btnCliente.IdleBorderThickness = 1;
            this.btnCliente.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnCliente.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCliente.IdleIconLeftImage")));
            this.btnCliente.IdleIconRightImage = null;
            this.btnCliente.IndicateFocus = false;
            this.btnCliente.Location = new System.Drawing.Point(8, 226);
            this.btnCliente.Margin = new System.Windows.Forms.Padding(5, 2, 3, 2);
            this.btnCliente.Name = "btnCliente";
            this.btnCliente.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCliente.OnDisabledState.BorderRadius = 1;
            this.btnCliente.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCliente.OnDisabledState.BorderThickness = 1;
            this.btnCliente.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCliente.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCliente.OnDisabledState.IconLeftImage = null;
            this.btnCliente.OnDisabledState.IconRightImage = null;
            this.btnCliente.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnCliente.onHoverState.BorderRadius = 1;
            this.btnCliente.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCliente.onHoverState.BorderThickness = 1;
            this.btnCliente.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnCliente.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCliente.onHoverState.IconLeftImage = null;
            this.btnCliente.onHoverState.IconRightImage = null;
            this.btnCliente.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnCliente.OnIdleState.BorderRadius = 1;
            this.btnCliente.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCliente.OnIdleState.BorderThickness = 1;
            this.btnCliente.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnCliente.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCliente.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCliente.OnIdleState.IconLeftImage")));
            this.btnCliente.OnIdleState.IconRightImage = null;
            this.btnCliente.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnCliente.OnPressedState.BorderRadius = 1;
            this.btnCliente.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnCliente.OnPressedState.BorderThickness = 1;
            this.btnCliente.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnCliente.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCliente.OnPressedState.IconLeftImage = null;
            this.btnCliente.OnPressedState.IconRightImage = null;
            this.btnCliente.Size = new System.Drawing.Size(267, 43);
            this.btnCliente.TabIndex = 5;
            this.btnCliente.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCliente.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCliente.TextMarginLeft = 0;
            this.btnCliente.TextPadding = new System.Windows.Forms.Padding(56, 4, 0, 2);
            this.btnCliente.UseDefaultRadiusAndThickness = true;
            this.btnCliente.Click += new System.EventHandler(this.btnCliente_Click);
            // 
            // btnDashboard
            // 
            this.btnDashboard.AllowAnimations = true;
            this.btnDashboard.AllowMouseEffects = true;
            this.btnDashboard.AllowToggling = false;
            this.btnDashboard.AnimationSpeed = 200;
            this.btnDashboard.AutoGenerateColors = false;
            this.btnDashboard.AutoRoundBorders = false;
            this.btnDashboard.AutoSizeLeftIcon = true;
            this.btnDashboard.AutoSizeRightIcon = true;
            this.btnDashboard.BackColor = System.Drawing.Color.Transparent;
            this.btnDashboard.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnDashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDashboard.BackgroundImage")));
            this.btnDashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDashboard.ButtonText = "Dashboard";
            this.btnDashboard.ButtonTextMarginLeft = 0;
            this.btnDashboard.ColorContrastOnClick = 45;
            this.btnDashboard.ColorContrastOnHover = 45;
            this.btnDashboard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnDashboard.CustomizableEdges = borderEdges8;
            this.btnDashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnDashboard.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDashboard.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconLeftPadding = new System.Windows.Forms.Padding(32, 3, 3, 3);
            this.btnDashboard.IconMarginLeft = 11;
            this.btnDashboard.IconPadding = 10;
            this.btnDashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDashboard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDashboard.IconSize = 15;
            this.btnDashboard.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnDashboard.IdleBorderRadius = 1;
            this.btnDashboard.IdleBorderThickness = 1;
            this.btnDashboard.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnDashboard.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDashboard.IdleIconLeftImage")));
            this.btnDashboard.IdleIconRightImage = null;
            this.btnDashboard.IndicateFocus = false;
            this.btnDashboard.Location = new System.Drawing.Point(5, 166);
            this.btnDashboard.Margin = new System.Windows.Forms.Padding(5, 2, 3, 2);
            this.btnDashboard.Name = "btnDashboard";
            this.btnDashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDashboard.OnDisabledState.BorderRadius = 1;
            this.btnDashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDashboard.OnDisabledState.BorderThickness = 1;
            this.btnDashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDashboard.OnDisabledState.IconLeftImage = null;
            this.btnDashboard.OnDisabledState.IconRightImage = null;
            this.btnDashboard.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnDashboard.onHoverState.BorderRadius = 1;
            this.btnDashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDashboard.onHoverState.BorderThickness = 1;
            this.btnDashboard.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(22)))), ((int)(((byte)(38)))));
            this.btnDashboard.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.onHoverState.IconLeftImage = null;
            this.btnDashboard.onHoverState.IconRightImage = null;
            this.btnDashboard.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnDashboard.OnIdleState.BorderRadius = 1;
            this.btnDashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDashboard.OnIdleState.BorderThickness = 1;
            this.btnDashboard.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.btnDashboard.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDashboard.OnIdleState.IconLeftImage")));
            this.btnDashboard.OnIdleState.IconRightImage = null;
            this.btnDashboard.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnDashboard.OnPressedState.BorderRadius = 1;
            this.btnDashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnDashboard.OnPressedState.BorderThickness = 1;
            this.btnDashboard.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnDashboard.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDashboard.OnPressedState.IconLeftImage = null;
            this.btnDashboard.OnPressedState.IconRightImage = null;
            this.btnDashboard.Size = new System.Drawing.Size(269, 43);
            this.btnDashboard.TabIndex = 0;
            this.btnDashboard.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDashboard.TextMarginLeft = 0;
            this.btnDashboard.TextPadding = new System.Windows.Forms.Padding(56, 4, 0, 2);
            this.btnDashboard.UseDefaultRadiusAndThickness = true;
            this.btnDashboard.Click += new System.EventHandler(this.btnDashboard_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.pictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.pictureBox1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(45, 33);
            this.pictureBox1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(224, 110);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 4;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuPanel4
            // 
            this.bunifuPanel4.AutoScroll = true;
            this.bunifuPanel4.AutoSize = true;
            this.bunifuPanel4.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(245)))), ((int)(((byte)(253)))));
            this.bunifuPanel4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel4.BackgroundImage")));
            this.bunifuPanel4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(245)))), ((int)(((byte)(253)))));
            this.bunifuPanel4.BorderRadius = 3;
            this.bunifuPanel4.BorderThickness = 1;
            this.bunifuPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel4.Location = new System.Drawing.Point(320, 0);
            this.bunifuPanel4.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuPanel4.Name = "bunifuPanel4";
            this.bunifuPanel4.ShowBorders = true;
            this.bunifuPanel4.Size = new System.Drawing.Size(1604, 786);
            this.bunifuPanel4.TabIndex = 20;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.BackColor = System.Drawing.SystemColors.ButtonFace;
            this.tableLayoutPanel1.ColumnCount = 2;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 320F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 1604F));
            this.tableLayoutPanel1.Controls.Add(this.bunifuPanel1, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.bunifuPanel4, 1, 0);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 1;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(1924, 786);
            this.tableLayoutPanel1.TabIndex = 0;
            // 
            // Layout
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.AutoSize = true;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(17)))), ((int)(((byte)(75)))), ((int)(((byte)(98)))));
            this.ClientSize = new System.Drawing.Size(1924, 786);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Controls.Add(this.btnUsuario);
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.MinimumSize = new System.Drawing.Size(450, 648);
            this.Name = "Layout";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Impdoor";
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.Layout_FormClosed);
            this.Load += new System.EventHandler(this.Layout_Load);
            this.bunifuPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnUsuario;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnUsuarios;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnMateriales;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnNCF;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnFacturas;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnVentas;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnCliente;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnDashboard;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel4;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
    }
}