namespace Capa_P
{
    partial class NCF
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(NCF));
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.dtaFiscal = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.txtFiltroNCF = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnEditar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnborrar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnlimpiar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnGuardarClienteR = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtNumerosCreditoFiscal = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblNombre = new System.Windows.Forms.Label();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblId = new System.Windows.Forms.Label();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtaFiscal)).BeginInit();
            this.SuspendLayout();
            // 
            // pictureBox1
            // 
            this.pictureBox1.BackColor = System.Drawing.Color.White;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(530, 377);
            this.pictureBox1.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(23, 20);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 114;
            this.pictureBox1.TabStop = false;
            // 
            // dtaFiscal
            // 
            this.dtaFiscal.AllowCustomTheming = false;
            this.dtaFiscal.AllowUserToAddRows = false;
            this.dtaFiscal.AllowUserToDeleteRows = false;
            this.dtaFiscal.AllowUserToResizeColumns = false;
            this.dtaFiscal.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dtaFiscal.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dtaFiscal.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtaFiscal.BackgroundColor = System.Drawing.Color.White;
            this.dtaFiscal.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtaFiscal.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtaFiscal.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtaFiscal.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dtaFiscal.ColumnHeadersHeight = 40;
            this.dtaFiscal.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dtaFiscal.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtaFiscal.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtaFiscal.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtaFiscal.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dtaFiscal.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dtaFiscal.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtaFiscal.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dtaFiscal.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtaFiscal.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dtaFiscal.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dtaFiscal.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dtaFiscal.CurrentTheme.Name = null;
            this.dtaFiscal.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dtaFiscal.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtaFiscal.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtaFiscal.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtaFiscal.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtaFiscal.DefaultCellStyle = dataGridViewCellStyle3;
            this.dtaFiscal.EnableHeadersVisualStyles = false;
            this.dtaFiscal.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtaFiscal.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dtaFiscal.HeaderBgColor = System.Drawing.Color.Empty;
            this.dtaFiscal.HeaderForeColor = System.Drawing.Color.White;
            this.dtaFiscal.Location = new System.Drawing.Point(90, 454);
            this.dtaFiscal.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.dtaFiscal.MultiSelect = false;
            this.dtaFiscal.Name = "dtaFiscal";
            this.dtaFiscal.ReadOnly = true;
            this.dtaFiscal.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(236)))), ((int)(((byte)(236)))));
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtaFiscal.RowHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.dtaFiscal.RowHeadersVisible = false;
            this.dtaFiscal.RowHeadersWidth = 51;
            this.dtaFiscal.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.DisableResizing;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            this.dtaFiscal.RowsDefaultCellStyle = dataGridViewCellStyle5;
            this.dtaFiscal.RowTemplate.Height = 40;
            this.dtaFiscal.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtaFiscal.Size = new System.Drawing.Size(957, 238);
            this.dtaFiscal.TabIndex = 112;
            this.dtaFiscal.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dtaFiscal.CellMouseClick += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.dtaFiscal_CellMouseClick);
            this.dtaFiscal.SelectionChanged += new System.EventHandler(this.dtaFiscal_SelectionChanged);
            // 
            // txtFiltroNCF
            // 
            this.txtFiltroNCF.AcceptsReturn = false;
            this.txtFiltroNCF.AcceptsTab = false;
            this.txtFiltroNCF.AnimationSpeed = 200;
            this.txtFiltroNCF.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtFiltroNCF.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtFiltroNCF.AutoSizeHeight = true;
            this.txtFiltroNCF.BackColor = System.Drawing.Color.Transparent;
            this.txtFiltroNCF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtFiltroNCF.BackgroundImage")));
            this.txtFiltroNCF.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtFiltroNCF.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtFiltroNCF.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtFiltroNCF.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtFiltroNCF.BorderRadius = 15;
            this.txtFiltroNCF.BorderThickness = 1;
            this.txtFiltroNCF.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtFiltroNCF.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtFiltroNCF.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltroNCF.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtFiltroNCF.DefaultText = "";
            this.txtFiltroNCF.FillColor = System.Drawing.Color.White;
            this.txtFiltroNCF.HideSelection = true;
            this.txtFiltroNCF.IconLeft = null;
            this.txtFiltroNCF.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltroNCF.IconPadding = 10;
            this.txtFiltroNCF.IconRight = null;
            this.txtFiltroNCF.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtFiltroNCF.Lines = new string[0];
            this.txtFiltroNCF.Location = new System.Drawing.Point(190, 364);
            this.txtFiltroNCF.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtFiltroNCF.MaxLength = 32767;
            this.txtFiltroNCF.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtFiltroNCF.Modified = false;
            this.txtFiltroNCF.Multiline = false;
            this.txtFiltroNCF.Name = "txtFiltroNCF";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltroNCF.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtFiltroNCF.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltroNCF.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Transparent;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtFiltroNCF.OnIdleState = stateProperties4;
            this.txtFiltroNCF.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtFiltroNCF.PasswordChar = '\0';
            this.txtFiltroNCF.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtFiltroNCF.PlaceholderText = "Buscar";
            this.txtFiltroNCF.ReadOnly = false;
            this.txtFiltroNCF.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtFiltroNCF.SelectedText = "";
            this.txtFiltroNCF.SelectionLength = 0;
            this.txtFiltroNCF.SelectionStart = 0;
            this.txtFiltroNCF.ShortcutsEnabled = true;
            this.txtFiltroNCF.Size = new System.Drawing.Size(381, 46);
            this.txtFiltroNCF.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtFiltroNCF.TabIndex = 111;
            this.txtFiltroNCF.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtFiltroNCF.TextMarginBottom = 0;
            this.txtFiltroNCF.TextMarginLeft = 3;
            this.txtFiltroNCF.TextMarginTop = 1;
            this.txtFiltroNCF.TextPlaceholder = "Buscar";
            this.txtFiltroNCF.UseSystemPasswordChar = false;
            this.txtFiltroNCF.WordWrap = true;
            this.txtFiltroNCF.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            // 
            // btnEditar
            // 
            this.btnEditar.AllowAnimations = true;
            this.btnEditar.AllowMouseEffects = true;
            this.btnEditar.AllowToggling = false;
            this.btnEditar.AnimationSpeed = 200;
            this.btnEditar.AutoGenerateColors = false;
            this.btnEditar.AutoRoundBorders = false;
            this.btnEditar.AutoSizeLeftIcon = true;
            this.btnEditar.AutoSizeRightIcon = true;
            this.btnEditar.BackColor = System.Drawing.Color.Transparent;
            this.btnEditar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnEditar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEditar.BackgroundImage")));
            this.btnEditar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.ButtonText = "Editar";
            this.btnEditar.ButtonTextMarginLeft = 0;
            this.btnEditar.ColorContrastOnClick = 45;
            this.btnEditar.ColorContrastOnHover = 45;
            this.btnEditar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnEditar.CustomizableEdges = borderEdges1;
            this.btnEditar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEditar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnEditar.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEditar.ForeColor = System.Drawing.Color.White;
            this.btnEditar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEditar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEditar.IconMarginLeft = 11;
            this.btnEditar.IconPadding = 10;
            this.btnEditar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEditar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEditar.IconSize = 25;
            this.btnEditar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnEditar.IdleBorderRadius = 20;
            this.btnEditar.IdleBorderThickness = 1;
            this.btnEditar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnEditar.IdleIconLeftImage = null;
            this.btnEditar.IdleIconRightImage = null;
            this.btnEditar.IndicateFocus = false;
            this.btnEditar.Location = new System.Drawing.Point(604, 377);
            this.btnEditar.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnEditar.Name = "btnEditar";
            this.btnEditar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEditar.OnDisabledState.BorderRadius = 20;
            this.btnEditar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.OnDisabledState.BorderThickness = 1;
            this.btnEditar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEditar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEditar.OnDisabledState.IconLeftImage = null;
            this.btnEditar.OnDisabledState.IconRightImage = null;
            this.btnEditar.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnEditar.onHoverState.BorderRadius = 20;
            this.btnEditar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.onHoverState.BorderThickness = 1;
            this.btnEditar.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnEditar.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnEditar.onHoverState.IconLeftImage = null;
            this.btnEditar.onHoverState.IconRightImage = null;
            this.btnEditar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnEditar.OnIdleState.BorderRadius = 20;
            this.btnEditar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.OnIdleState.BorderThickness = 1;
            this.btnEditar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnEditar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEditar.OnIdleState.IconLeftImage = null;
            this.btnEditar.OnIdleState.IconRightImage = null;
            this.btnEditar.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnEditar.OnPressedState.BorderRadius = 20;
            this.btnEditar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnEditar.OnPressedState.BorderThickness = 1;
            this.btnEditar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnEditar.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btnEditar.OnPressedState.IconLeftImage = null;
            this.btnEditar.OnPressedState.IconRightImage = null;
            this.btnEditar.Size = new System.Drawing.Size(127, 32);
            this.btnEditar.TabIndex = 110;
            this.btnEditar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEditar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEditar.TextMarginLeft = 0;
            this.btnEditar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEditar.UseDefaultRadiusAndThickness = true;
            this.btnEditar.Click += new System.EventHandler(this.btnEditar_Click);
            // 
            // btnborrar
            // 
            this.btnborrar.AllowAnimations = true;
            this.btnborrar.AllowMouseEffects = true;
            this.btnborrar.AllowToggling = false;
            this.btnborrar.AnimationSpeed = 200;
            this.btnborrar.AutoGenerateColors = false;
            this.btnborrar.AutoRoundBorders = false;
            this.btnborrar.AutoSizeLeftIcon = true;
            this.btnborrar.AutoSizeRightIcon = true;
            this.btnborrar.BackColor = System.Drawing.Color.Transparent;
            this.btnborrar.BackColor1 = System.Drawing.Color.Red;
            this.btnborrar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnborrar.BackgroundImage")));
            this.btnborrar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.ButtonText = "Borrar";
            this.btnborrar.ButtonTextMarginLeft = 0;
            this.btnborrar.ColorContrastOnClick = 45;
            this.btnborrar.ColorContrastOnHover = 45;
            this.btnborrar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnborrar.CustomizableEdges = borderEdges2;
            this.btnborrar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnborrar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnborrar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnborrar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnborrar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnborrar.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnborrar.ForeColor = System.Drawing.Color.White;
            this.btnborrar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnborrar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnborrar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnborrar.IconMarginLeft = 11;
            this.btnborrar.IconPadding = 10;
            this.btnborrar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnborrar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnborrar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnborrar.IconSize = 25;
            this.btnborrar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnborrar.IdleBorderRadius = 20;
            this.btnborrar.IdleBorderThickness = 1;
            this.btnborrar.IdleFillColor = System.Drawing.Color.Red;
            this.btnborrar.IdleIconLeftImage = null;
            this.btnborrar.IdleIconRightImage = null;
            this.btnborrar.IndicateFocus = false;
            this.btnborrar.Location = new System.Drawing.Point(772, 334);
            this.btnborrar.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnborrar.Name = "btnborrar";
            this.btnborrar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnborrar.OnDisabledState.BorderRadius = 20;
            this.btnborrar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.OnDisabledState.BorderThickness = 1;
            this.btnborrar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnborrar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnborrar.OnDisabledState.IconLeftImage = null;
            this.btnborrar.OnDisabledState.IconRightImage = null;
            this.btnborrar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnborrar.onHoverState.BorderRadius = 20;
            this.btnborrar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.onHoverState.BorderThickness = 1;
            this.btnborrar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnborrar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnborrar.onHoverState.IconLeftImage = null;
            this.btnborrar.onHoverState.IconRightImage = null;
            this.btnborrar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnborrar.OnIdleState.BorderRadius = 20;
            this.btnborrar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.OnIdleState.BorderThickness = 1;
            this.btnborrar.OnIdleState.FillColor = System.Drawing.Color.Red;
            this.btnborrar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnborrar.OnIdleState.IconLeftImage = null;
            this.btnborrar.OnIdleState.IconRightImage = null;
            this.btnborrar.OnPressedState.BorderColor = System.Drawing.Color.Red;
            this.btnborrar.OnPressedState.BorderRadius = 20;
            this.btnborrar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnborrar.OnPressedState.BorderThickness = 1;
            this.btnborrar.OnPressedState.FillColor = System.Drawing.Color.Red;
            this.btnborrar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnborrar.OnPressedState.IconLeftImage = null;
            this.btnborrar.OnPressedState.IconRightImage = null;
            this.btnborrar.Size = new System.Drawing.Size(119, 32);
            this.btnborrar.TabIndex = 109;
            this.btnborrar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnborrar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnborrar.TextMarginLeft = 0;
            this.btnborrar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnborrar.UseDefaultRadiusAndThickness = true;
            this.btnborrar.Click += new System.EventHandler(this.btnborrar_Click);
            // 
            // btnlimpiar
            // 
            this.btnlimpiar.AllowAnimations = true;
            this.btnlimpiar.AllowMouseEffects = true;
            this.btnlimpiar.AllowToggling = false;
            this.btnlimpiar.AnimationSpeed = 200;
            this.btnlimpiar.AutoGenerateColors = false;
            this.btnlimpiar.AutoRoundBorders = false;
            this.btnlimpiar.AutoSizeLeftIcon = true;
            this.btnlimpiar.AutoSizeRightIcon = true;
            this.btnlimpiar.BackColor = System.Drawing.Color.Transparent;
            this.btnlimpiar.BackColor1 = System.Drawing.Color.White;
            this.btnlimpiar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnlimpiar.BackgroundImage")));
            this.btnlimpiar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.ButtonText = "Limpiar";
            this.btnlimpiar.ButtonTextMarginLeft = 0;
            this.btnlimpiar.ColorContrastOnClick = 45;
            this.btnlimpiar.ColorContrastOnHover = 45;
            this.btnlimpiar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnlimpiar.CustomizableEdges = borderEdges3;
            this.btnlimpiar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnlimpiar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnlimpiar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnlimpiar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnlimpiar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnlimpiar.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnlimpiar.ForeColor = System.Drawing.Color.DimGray;
            this.btnlimpiar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnlimpiar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnlimpiar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnlimpiar.IconMarginLeft = 11;
            this.btnlimpiar.IconPadding = 10;
            this.btnlimpiar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnlimpiar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnlimpiar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnlimpiar.IconSize = 25;
            this.btnlimpiar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnlimpiar.IdleBorderRadius = 20;
            this.btnlimpiar.IdleBorderThickness = 1;
            this.btnlimpiar.IdleFillColor = System.Drawing.Color.White;
            this.btnlimpiar.IdleIconLeftImage = null;
            this.btnlimpiar.IdleIconRightImage = null;
            this.btnlimpiar.IndicateFocus = false;
            this.btnlimpiar.Location = new System.Drawing.Point(604, 334);
            this.btnlimpiar.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnlimpiar.Name = "btnlimpiar";
            this.btnlimpiar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnlimpiar.OnDisabledState.BorderRadius = 20;
            this.btnlimpiar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.OnDisabledState.BorderThickness = 1;
            this.btnlimpiar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnlimpiar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnlimpiar.OnDisabledState.IconLeftImage = null;
            this.btnlimpiar.OnDisabledState.IconRightImage = null;
            this.btnlimpiar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(170)))), ((int)(((byte)(170)))));
            this.btnlimpiar.onHoverState.BorderRadius = 20;
            this.btnlimpiar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.onHoverState.BorderThickness = 1;
            this.btnlimpiar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(170)))), ((int)(((byte)(170)))));
            this.btnlimpiar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnlimpiar.onHoverState.IconLeftImage = null;
            this.btnlimpiar.onHoverState.IconRightImage = null;
            this.btnlimpiar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnlimpiar.OnIdleState.BorderRadius = 20;
            this.btnlimpiar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.OnIdleState.BorderThickness = 1;
            this.btnlimpiar.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnlimpiar.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.btnlimpiar.OnIdleState.IconLeftImage = null;
            this.btnlimpiar.OnIdleState.IconRightImage = null;
            this.btnlimpiar.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnlimpiar.OnPressedState.BorderRadius = 20;
            this.btnlimpiar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnlimpiar.OnPressedState.BorderThickness = 1;
            this.btnlimpiar.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnlimpiar.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.btnlimpiar.OnPressedState.IconLeftImage = null;
            this.btnlimpiar.OnPressedState.IconRightImage = null;
            this.btnlimpiar.Size = new System.Drawing.Size(127, 32);
            this.btnlimpiar.TabIndex = 108;
            this.btnlimpiar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnlimpiar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnlimpiar.TextMarginLeft = 0;
            this.btnlimpiar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnlimpiar.UseDefaultRadiusAndThickness = true;
            this.btnlimpiar.Click += new System.EventHandler(this.btnlimpiar_Click);
            // 
            // btnGuardarClienteR
            // 
            this.btnGuardarClienteR.AllowAnimations = true;
            this.btnGuardarClienteR.AllowMouseEffects = true;
            this.btnGuardarClienteR.AllowToggling = false;
            this.btnGuardarClienteR.AnimationSpeed = 200;
            this.btnGuardarClienteR.AutoGenerateColors = false;
            this.btnGuardarClienteR.AutoRoundBorders = false;
            this.btnGuardarClienteR.AutoSizeLeftIcon = true;
            this.btnGuardarClienteR.AutoSizeRightIcon = true;
            this.btnGuardarClienteR.BackColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuardarClienteR.BackgroundImage")));
            this.btnGuardarClienteR.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.ButtonText = "Guardar";
            this.btnGuardarClienteR.ButtonTextMarginLeft = 0;
            this.btnGuardarClienteR.ColorContrastOnClick = 45;
            this.btnGuardarClienteR.ColorContrastOnHover = 45;
            this.btnGuardarClienteR.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnGuardarClienteR.CustomizableEdges = borderEdges4;
            this.btnGuardarClienteR.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuardarClienteR.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardarClienteR.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardarClienteR.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardarClienteR.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.btnGuardarClienteR.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardarClienteR.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuardarClienteR.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardarClienteR.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGuardarClienteR.IconMarginLeft = 11;
            this.btnGuardarClienteR.IconPadding = 10;
            this.btnGuardarClienteR.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGuardarClienteR.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardarClienteR.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGuardarClienteR.IconSize = 25;
            this.btnGuardarClienteR.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.IdleBorderRadius = 20;
            this.btnGuardarClienteR.IdleBorderThickness = 1;
            this.btnGuardarClienteR.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.IdleIconLeftImage = null;
            this.btnGuardarClienteR.IdleIconRightImage = null;
            this.btnGuardarClienteR.IndicateFocus = false;
            this.btnGuardarClienteR.Location = new System.Drawing.Point(593, 103);
            this.btnGuardarClienteR.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.btnGuardarClienteR.Name = "btnGuardarClienteR";
            this.btnGuardarClienteR.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardarClienteR.OnDisabledState.BorderRadius = 20;
            this.btnGuardarClienteR.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnDisabledState.BorderThickness = 1;
            this.btnGuardarClienteR.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardarClienteR.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardarClienteR.OnDisabledState.IconLeftImage = null;
            this.btnGuardarClienteR.OnDisabledState.IconRightImage = null;
            this.btnGuardarClienteR.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.onHoverState.BorderRadius = 20;
            this.btnGuardarClienteR.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.onHoverState.BorderThickness = 1;
            this.btnGuardarClienteR.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnGuardarClienteR.onHoverState.IconLeftImage = null;
            this.btnGuardarClienteR.onHoverState.IconRightImage = null;
            this.btnGuardarClienteR.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnGuardarClienteR.OnIdleState.BorderRadius = 20;
            this.btnGuardarClienteR.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnIdleState.BorderThickness = 1;
            this.btnGuardarClienteR.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.OnIdleState.IconLeftImage = null;
            this.btnGuardarClienteR.OnIdleState.IconRightImage = null;
            this.btnGuardarClienteR.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnPressedState.BorderRadius = 20;
            this.btnGuardarClienteR.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardarClienteR.OnPressedState.BorderThickness = 1;
            this.btnGuardarClienteR.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.btnGuardarClienteR.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGuardarClienteR.OnPressedState.IconLeftImage = null;
            this.btnGuardarClienteR.OnPressedState.IconRightImage = null;
            this.btnGuardarClienteR.Size = new System.Drawing.Size(141, 39);
            this.btnGuardarClienteR.TabIndex = 107;
            this.btnGuardarClienteR.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuardarClienteR.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGuardarClienteR.TextMarginLeft = 0;
            this.btnGuardarClienteR.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGuardarClienteR.UseDefaultRadiusAndThickness = true;
            this.btnGuardarClienteR.Click += new System.EventHandler(this.btnGuardarClienteR_Click);
            // 
            // txtNumerosCreditoFiscal
            // 
            this.txtNumerosCreditoFiscal.AcceptsReturn = false;
            this.txtNumerosCreditoFiscal.AcceptsTab = false;
            this.txtNumerosCreditoFiscal.AnimationSpeed = 200;
            this.txtNumerosCreditoFiscal.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNumerosCreditoFiscal.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNumerosCreditoFiscal.AutoSizeHeight = true;
            this.txtNumerosCreditoFiscal.BackColor = System.Drawing.Color.Transparent;
            this.txtNumerosCreditoFiscal.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNumerosCreditoFiscal.BackgroundImage")));
            this.txtNumerosCreditoFiscal.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNumerosCreditoFiscal.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNumerosCreditoFiscal.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNumerosCreditoFiscal.BorderColorIdle = System.Drawing.Color.Transparent;
            this.txtNumerosCreditoFiscal.BorderRadius = 20;
            this.txtNumerosCreditoFiscal.BorderThickness = 1;
            this.txtNumerosCreditoFiscal.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNumerosCreditoFiscal.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNumerosCreditoFiscal.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumerosCreditoFiscal.DefaultFont = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNumerosCreditoFiscal.DefaultText = "";
            this.txtNumerosCreditoFiscal.FillColor = System.Drawing.Color.White;
            this.txtNumerosCreditoFiscal.HideSelection = true;
            this.txtNumerosCreditoFiscal.IconLeft = null;
            this.txtNumerosCreditoFiscal.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumerosCreditoFiscal.IconPadding = 10;
            this.txtNumerosCreditoFiscal.IconRight = null;
            this.txtNumerosCreditoFiscal.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumerosCreditoFiscal.Lines = new string[0];
            this.txtNumerosCreditoFiscal.Location = new System.Drawing.Point(190, 103);
            this.txtNumerosCreditoFiscal.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtNumerosCreditoFiscal.MaxLength = 32767;
            this.txtNumerosCreditoFiscal.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNumerosCreditoFiscal.Modified = false;
            this.txtNumerosCreditoFiscal.Multiline = true;
            this.txtNumerosCreditoFiscal.Name = "txtNumerosCreditoFiscal";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumerosCreditoFiscal.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNumerosCreditoFiscal.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumerosCreditoFiscal.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Transparent;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumerosCreditoFiscal.OnIdleState = stateProperties8;
            this.txtNumerosCreditoFiscal.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.txtNumerosCreditoFiscal.PasswordChar = '\0';
            this.txtNumerosCreditoFiscal.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNumerosCreditoFiscal.PlaceholderText = "NCF B0100000262";
            this.txtNumerosCreditoFiscal.ReadOnly = false;
            this.txtNumerosCreditoFiscal.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNumerosCreditoFiscal.SelectedText = "";
            this.txtNumerosCreditoFiscal.SelectionLength = 0;
            this.txtNumerosCreditoFiscal.SelectionStart = 0;
            this.txtNumerosCreditoFiscal.ShortcutsEnabled = true;
            this.txtNumerosCreditoFiscal.Size = new System.Drawing.Size(381, 204);
            this.txtNumerosCreditoFiscal.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNumerosCreditoFiscal.TabIndex = 106;
            this.txtNumerosCreditoFiscal.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNumerosCreditoFiscal.TextMarginBottom = 0;
            this.txtNumerosCreditoFiscal.TextMarginLeft = 3;
            this.txtNumerosCreditoFiscal.TextMarginTop = 1;
            this.txtNumerosCreditoFiscal.TextPlaceholder = "NCF B0100000262";
            this.txtNumerosCreditoFiscal.UseSystemPasswordChar = false;
            this.txtNumerosCreditoFiscal.WordWrap = true;
            // 
            // lblNombre
            // 
            this.lblNombre.Font = new System.Drawing.Font("Microsoft Sans Serif", 13.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblNombre.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.lblNombre.Location = new System.Drawing.Point(85, 103);
            this.lblNombre.Name = "lblNombre";
            this.lblNombre.Size = new System.Drawing.Size(89, 39);
            this.lblNombre.TabIndex = 105;
            this.lblNombre.Text = "Código";
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 16.2F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(32)))), ((int)(((byte)(51)))));
            this.bunifuLabel2.Location = new System.Drawing.Point(90, 30);
            this.bunifuLabel2.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(181, 31);
            this.bunifuLabel2.TabIndex = 104;
            this.bunifuLabel2.Text = "Crédito Fiscal ";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblId
            // 
            this.lblId.BackColor = System.Drawing.Color.White;
            this.lblId.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lblId.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblId.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.lblId.Location = new System.Drawing.Point(786, 52);
            this.lblId.Name = "lblId";
            this.lblId.Size = new System.Drawing.Size(141, 25);
            this.lblId.TabIndex = 103;
            this.lblId.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lblId.Visible = false;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Exportar";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges5;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Disabled;
            this.bunifuButton21.Font = new System.Drawing.Font("Microsoft Sans Serif", 10.2F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.IdleBorderRadius = 20;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(895, 413);
            this.bunifuButton21.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 20;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(170)))), ((int)(((byte)(170)))));
            this.bunifuButton21.onHoverState.BorderRadius = 20;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(170)))), ((int)(((byte)(170)))), ((int)(((byte)(170)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.OnIdleState.BorderRadius = 20;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.BorderRadius = 20;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.DimGray;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(127, 32);
            this.bunifuButton21.TabIndex = 115;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // NCF
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1604, 738);
            this.Controls.Add(this.bunifuButton21);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.dtaFiscal);
            this.Controls.Add(this.txtFiltroNCF);
            this.Controls.Add(this.btnEditar);
            this.Controls.Add(this.btnborrar);
            this.Controls.Add(this.btnlimpiar);
            this.Controls.Add(this.btnGuardarClienteR);
            this.Controls.Add(this.txtNumerosCreditoFiscal);
            this.Controls.Add(this.lblNombre);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.lblId);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Name = "NCF";
            this.Text = "NCF";
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dtaFiscal)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuDataGridView dtaFiscal;
        private Bunifu.UI.WinForms.BunifuTextBox txtFiltroNCF;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnEditar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnborrar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnlimpiar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnGuardarClienteR;
        private Bunifu.UI.WinForms.BunifuTextBox txtNumerosCreditoFiscal;
        private System.Windows.Forms.Label lblNombre;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private System.Windows.Forms.Label lblId;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
    }
}